/*
 @product.name@ JS v@product.version@ (@product.date@)

 (c) 2009-2014 Torstein Honsi

 License: www.highcharts.com/license
 @product.name@ JS v@product.version@ (@product.date@)
 Exporting module

 (c) 2010-2014 Torstein Honsi

 License: www.highcharts.com/license
 @product.name@ JS v@product.version@ (@product.date@)

 (c) 2011-2014 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(){function s(a,b){var c;a||(a={});for(c in b)a[c]=b[c];return a}function E(){var a,b=arguments,c,d={},e=function(a,b){var c,d;"object"!==typeof a&&(a={});for(d in b)b.hasOwnProperty(d)&&((c=b[d])&&"object"===typeof c&&"[object Array]"!==Object.prototype.toString.call(c)&&"renderTo"!==d&&"number"!==typeof c.nodeType?a[d]=e(a[d]||{},c):a[d]=b[d]);return a};!0===b[0]&&(d=b[1],b=Array.prototype.slice.call(b,2));c=b.length;for(a=0;a<c;a++)d=e(d,b[a]);return d}function B(a,b){return parseInt(a,
b||10)}function fa(a){return"string"===typeof a}function J(a){return"object"===typeof a}function Y(a){return"[object Array]"===Object.prototype.toString.call(a)}function U(a){return"number"===typeof a}function R(a){return S.log(a)/S.LN10}function O(a){return S.pow(10,a)}function T(a,b){for(var c=a.length;c--;)if(a[c]===b){a.splice(c,1);break}}function u(a){return a!==A&&null!==a}function G(a,b,c){var d,e;if(fa(b))u(c)?a.setAttribute(b,c):a&&a.getAttribute&&(e=a.getAttribute(b));else if(u(b)&&J(b))for(d in b)a.setAttribute(d,
b[d]);return e}function ka(a){return Y(a)?a:[a]}function k(){var a=arguments,b,c,d=a.length;for(b=0;b<d;b++)if(c=a[b],"undefined"!==typeof c&&null!==c)return c}function K(a,b){na&&!$&&b&&b.opacity!==A&&(b.filter="alpha(opacity="+100*b.opacity+")");s(a.style,b)}function ia(a,b,c,d,e){a=F.createElement(a);b&&s(a,b);e&&K(a,{padding:0,border:aa,margin:0});c&&K(a,c);d&&d.appendChild(a);return a}function oa(a,b){var c=function(){};c.prototype=new a;s(c.prototype,b);return c}function x(a,b,c,d){var e=Q.lang;
a=+a||0;var f=-1===b?(a.toString().split(".")[1]||"").length:isNaN(b=la(b))?2:b;b=void 0===c?e.decimalPoint:c;d=void 0===d?e.thousandsSep:d;e=0>a?"-":"";c=String(B(a=la(a).toFixed(f)));var g=3<c.length?c.length%3:0;return e+(g?c.substr(0,g)+d:"")+c.substr(g).replace(/(\d{3})(?=\d)/g,"$1"+d)+(f?b+la(a-c).toFixed(f).slice(2):"")}function r(a,b){return Array((b||2)+1-String(a).length).join(0)+a}function L(a,b,c){var d=a[b];a[b]=function(){var a=Array.prototype.slice.call(arguments);a.unshift(d);return c.apply(this,
a)}}function y(a,b){for(var c="{",d=!1,e,f,g,h,l,m=[];-1!==(c=a.indexOf(c));){e=a.slice(0,c);if(d){f=e.split(":");g=f.shift().split(".");l=g.length;e=b;for(h=0;h<l;h++)e=e[g[h]];f.length&&(f=f.join(":"),g=/\.([0-9])/,h=Q.lang,l=void 0,/f$/.test(f)?(l=(l=f.match(g))?l[1]:-1,null!==e&&(e=x(e,l,h.decimalPoint,-1<f.indexOf(",")?h.thousandsSep:""))):e=za(f,e))}m.push(e);a=a.slice(c+1);c=(d=!d)?"}":"{"}m.push(a);return m.join("")}function hb(a,b,c,d){var e;c=k(c,1);e=a/c;b||(b=[1,2,2.5,5,10],d&&!1===d.allowDecimals&&
(1===c?b=[1,2,5,10]:0.1>=c&&(b=[1/c])));for(d=0;d<b.length&&!(a=b[d],e<=(b[d]+(b[d+1]||b[d]))/2);d++);return a*c}function Aa(){this.symbol=this.color=0}function D(a,b){var c=a.length,d,e;for(e=0;e<c;e++)a[e].ss_i=e;a.sort(function(a,c){d=b(a,c);return 0===d?a.ss_i-c.ss_i:d});for(e=0;e<c;e++)delete a[e].ss_i}function w(a){for(var b=a.length,c=a[0];b--;)a[b]<c&&(c=a[b]);return c}function ua(a){for(var b=a.length,c=a[0];b--;)a[b]>c&&(c=a[b]);return c}function pa(a,b){for(var c in a)a[c]&&a[c]!==b&&a[c].destroy&&
a[c].destroy(),delete a[c]}function qa(a){Ba||(Ba=ia(Qa));a&&Ba.appendChild(a);Ba.innerHTML=""}function I(a,b){var c="Highcharts error #"+a+": www.highcharts.com/errors/"+a;if(b)throw c;M.console&&console.log(c)}function Z(a){return parseFloat(a.toPrecision(14))}function P(){var a=Q.global.useUTC,b=a?"getUTC":"get";Ra=6E4*(a&&Q.global.timezoneOffset||0);Sa=b+"Minutes";Ta=b+"Hours";Ua=b+"Day";Va=b+"Date";Wa=b+"Month";Xa=b+"FullYear"}function N(){}function ba(a,b,c,d){this.axis=a;this.pos=b;this.type=
c||"";this.isNew=!0;c||d||this.addLabel()}function Ca(){this.init.apply(this,arguments)}function Ia(){this.init.apply(this,arguments)}var A,F=document,M=window,S=Math,C=S.round,ca=S.floor,ta=S.ceil,z=S.max,ga=S.min,la=S.abs,va=S.cos,Da=S.sin,Ya=S.PI,Za=2*Ya/360,ra=navigator.userAgent,ib=M.opera,na=/msie/i.test(ra)&&!ib,$a=/AppleWebKit/.test(ra),Ea=/Firefox/.test(ra),ab=/(Mobile|Android|Windows Phone)/.test(ra),$=!!F.createElementNS&&!!F.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect,
jb=Ea&&4>parseInt(ra.split("Firefox/")[1],10),ja=!$&&!na&&!!F.createElement("canvas").getContext,bb={},Ja=0,Ba,Q,za,da,Ka,ma=[],cb=0,Qa="div",aa="none",kb=/^[0-9]+$/,lb="stroke-width",Ra,Sa,Ta,Ua,Va,Wa,Xa,wa={},sa=M.Highcharts=M.Highcharts?I(16,!0):{};za=function(a,b,c){if(!u(b)||isNaN(b))return"Invalid date";a=k(a,"%Y-%m-%d %H:%M:%S");var d=new Date(b-Ra),e,f=d[Ta](),g=d[Ua](),h=d[Va](),l=d[Wa](),m=d[Xa](),q=Q.lang,p=q.weekdays,d=s({a:p[g].substr(0,3),A:p[g],d:r(h),e:h,b:q.shortMonths[l],B:q.months[l],
m:r(l+1),y:m.toString().substr(2,2),Y:m,H:r(f),I:r(f%12||12),l:f%12||12,M:r(d[Sa]()),p:12>f?"AM":"PM",P:12>f?"am":"pm",S:r(d.getSeconds()),L:r(C(b%1E3),3)},sa.dateFormats);for(e in d)for(;-1!==a.indexOf("%"+e);)a=a.replace("%"+e,"function"===typeof d[e]?d[e](b):d[e]);return c?a.substr(0,1).toUpperCase()+a.substr(1):a};Aa.prototype={wrapColor:function(a){this.color>=a&&(this.color=0)},wrapSymbol:function(a){this.symbol>=a&&(this.symbol=0)}};(function(){for(var a=0,b=arguments,c=b.length,d={};a<c;a++)d[b[a++]]=
b[a];return d})("millisecond",1,"second",1E3,"minute",6E4,"hour",36E5,"day",864E5,"week",6048E5,"month",26784E5,"year",31556952E3);Ka={init:function(a,b,c){b=b||"";var d=a.shift,e=-1<b.indexOf("C"),f=e?7:3,g;b=b.split(" ");c=[].concat(c);var h,l,m=function(a){for(g=a.length;g--;)"M"===a[g]&&a.splice(g+1,0,a[g+1],a[g+2],a[g+1],a[g+2])};e&&(m(b),m(c));a.isArea&&(h=b.splice(b.length-6,6),l=c.splice(c.length-6,6));if(d<=c.length/f&&b.length===c.length)for(;d--;)c=[].concat(c).splice(0,f).concat(c);a.shift=
0;if(b.length)for(a=c.length;b.length<a;)d=[].concat(b).splice(b.length-f,f),e&&(d[f-6]=d[f-2],d[f-5]=d[f-1]),b=b.concat(d);h&&(b=b.concat(h),c=c.concat(l));return[b,c]},step:function(a,b,c,d){var e=[],f=a.length;if(1===c)e=d;else if(f===b.length&&1>c)for(;f--;)d=parseFloat(a[f]),e[f]=isNaN(d)?a[f]:c*parseFloat(b[f]-d)+d;else e=b;return e}};(function(a){M.HighchartsAdapter=M.HighchartsAdapter||a&&{init:function(b){var c=a.fx,d=c.step,e,f=a.Tween,g=f&&f.propHooks;e=a.cssHooks.opacity;a.extend(a.easing,
{easeOutQuad:function(a,b,c,d,e){return-d*(b/=e)*(b-2)+c}});a.each(["cur","_default","width","height","opacity"],function(a,b){var e=d,q;"cur"===b?e=c.prototype:"_default"===b&&f&&(e=g[b],b="set");(q=e[b])&&(e[b]=function(c){var d;c=a?c:this;if("align"!==c.prop)return d=c.elem,d.attr?d.attr(c.prop,"cur"===b?A:c.now):q.apply(this,arguments)})});L(e,"get",function(a,b,c){return b.attr?b.opacity||0:a.call(this,b,c)});e=function(a){var c=a.elem,d;a.started||(d=b.init(c,c.d,c.toD),a.start=d[0],a.end=d[1],
a.started=!0);c.attr("d",b.step(a.start,a.end,a.pos,c.toD))};f?g.d={set:e}:d.d=e;this.each=Array.prototype.forEach?function(a,b){return Array.prototype.forEach.call(a,b)}:function(a,b){for(var c=0,d=a.length;c<d;c++)if(!1===b.call(a[c],a[c],c,a))return c};a.fn.highcharts=function(){var a="Chart",b=arguments,c,d;this[0]&&(fa(b[0])&&(a=b[0],b=Array.prototype.slice.call(b,1)),c=b[0],c!==A&&(c.chart=c.chart||{},c.chart.renderTo=this[0],new sa[a](c,b[1]),d=this),c===A&&(d=ma[G(this[0],"data-highcharts-chart")]));
return d}},getScript:a.getScript,inArray:a.inArray,adapterRun:function(b,c){return a(b)[c]()},grep:a.grep,map:function(a,c){for(var d=[],e=0,f=a.length;e<f;e++)d[e]=c.call(a[e],a[e],e,a);return d},offset:function(b){return a(b).offset()},addEvent:function(b,c,d){a(b).bind(c,d)},removeEvent:function(b,c,d){var e=F.removeEventListener?"removeEventListener":"detachEvent";F[e]&&b&&!b[e]&&(b[e]=function(){});a(b).unbind(c,d)},fireEvent:function(b,c,d,e){var f=a.Event(c),g="detached"+c,h;!na&&d&&(delete d.layerX,
delete d.layerY,delete d.returnValue);s(f,d);b[c]&&(b[g]=b[c],b[c]=null);a.each(["preventDefault","stopPropagation"],function(a,b){var c=f[b];f[b]=function(){try{c.call(f)}catch(a){"preventDefault"===b&&(h=!0)}}});a(b).trigger(f);b[g]&&(b[c]=b[g],b[g]=null);!e||f.isDefaultPrevented()||h||e(f)},washMouseEvent:function(a){var c=a.originalEvent||a;c.pageX===A&&(c.pageX=a.pageX,c.pageY=a.pageY);return c},animate:function(b,c,d){var e=a(b);b.style||(b.style={});c.d&&(b.toD=c.d,c.d=1);e.stop();c.opacity!==
A&&b.attr&&(c.opacity+="px");e.animate(c,d)},stop:function(b){a(b).stop()}}})(M.jQuery);var Fa=M.HighchartsAdapter,ha=Fa||{};Fa&&Fa.init.call(Fa,Ka);var Ga=ha.adapterRun,mb=ha.inArray,t=ha.each,db=ha.grep,eb=ha.map,V=ha.addEvent,ea=ha.removeEvent,W=ha.fireEvent,fb=ha.animate,La=ha.stop,Ma={enabled:!0,x:0,y:15,style:{color:"#606060",cursor:"default",fontSize:"11px"}};Q={colors:"#7cb5ec #434348 #90ed7d #f7a35c #8085e9 #f15c80 #e4d354 #8085e8 #8d4653 #91e8e1".split(" "),symbols:["circle","diamond","square",
"triangle","triangle-down"],lang:{loading:"Loading...",months:"January February March April May June July August September October November December".split(" "),shortMonths:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),weekdays:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),decimalPoint:".",numericSymbols:"kMGTPE".split(""),resetZoom:"Reset zoom",resetZoomTitle:"Reset zoom level 1:1",thousandsSep:","},global:{useUTC:!0,canvasToolsURL:"http://code.highcharts.com@product.cdnpath@/@product.version@/modules/canvas-tools.js",
VMLRadialGradientURL:"http://code.highcharts.com@product.cdnpath@/@product.version@/gfx/vml-radial-gradient.png"},chart:{borderColor:"#4572A7",borderRadius:0,defaultSeriesType:"line",ignoreHiddenSeries:!0,spacing:[10,10,15,10],backgroundColor:"#FFFFFF",plotBorderColor:"#C0C0C0",resetZoomButton:{theme:{zIndex:20},position:{align:"right",x:-10,y:10}}},title:{text:"Chart title",align:"center",margin:15,style:{color:"#333333",fontSize:"18px"}},subtitle:{text:"",align:"center",style:{color:"#555555"}},
plotOptions:{line:{allowPointSelect:!1,showCheckbox:!1,animation:{duration:1E3},events:{},lineWidth:2,marker:{lineWidth:0,radius:4,lineColor:"#FFFFFF",states:{hover:{enabled:!0},select:{fillColor:"#FFFFFF",lineColor:"#000000",lineWidth:2}}},point:{events:{}},dataLabels:E(Ma,{align:"center",enabled:!1,formatter:function(){return null===this.y?"":x(this.y,-1)},verticalAlign:"bottom",y:0}),cropThreshold:300,pointRange:0,states:{hover:{marker:{},halo:{size:10,opacity:0.25}},select:{marker:{}}},stickyTracking:!0,
turboThreshold:1E3}},labels:{style:{position:"absolute",color:"#3E576F"}},legend:{enabled:!0,align:"center",layout:"horizontal",labelFormatter:function(){return this.name},borderColor:"#909090",borderRadius:0,navigation:{activeColor:"#274b6d",inactiveColor:"#CCC"},shadow:!1,itemStyle:{color:"#333333",fontSize:"12px",fontWeight:"bold"},itemHoverStyle:{color:"#000"},itemHiddenStyle:{color:"#CCC"},itemCheckboxStyle:{position:"absolute",width:"13px",height:"13px"},symbolPadding:5,verticalAlign:"bottom",
x:0,y:0,title:{style:{fontWeight:"bold"}}},loading:{labelStyle:{fontWeight:"bold",position:"relative",top:"1em"},style:{position:"absolute",backgroundColor:"white",opacity:0.5,textAlign:"center"}},tooltip:{enabled:!0,animation:$,backgroundColor:"rgba(249, 249, 249, .85)",borderWidth:1,borderRadius:3,dateTimeLabelFormats:{millisecond:"%A, %b %e, %H:%M:%S.%L",second:"%A, %b %e, %H:%M:%S",minute:"%A, %b %e, %H:%M",hour:"%A, %b %e, %H:%M",day:"%A, %b %e, %Y",week:"Week from %A, %b %e, %Y",month:"%B %Y",
year:"%Y"},headerFormat:'<span style="font-size: 10px">{point.key}</span><br/>',pointFormat:'<span style="color:{series.color}">\u25cf</span> {series.name}: <b>{point.y}</b><br/>',shadow:!0,snap:ab?25:10,style:{color:"#333333",cursor:"default",fontSize:"12px",padding:"8px",whiteSpace:"nowrap"}},credits:{enabled:!0,text:"Highcharts.com",href:"http://www.highcharts.com",position:{align:"right",x:-10,verticalAlign:"bottom",y:-5},style:{cursor:"pointer",color:"#909090",fontSize:"9px"}}};var Na=Q.plotOptions;
P();var nb=/rgba\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]?(?:\.[0-9]+)?)\s*\)/,ob=/#([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})/,pb=/rgb\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*\)/,xa=function(a){var b=[],c,d;(function(a){a&&a.stops?d=eb(a.stops,function(a){return xa(a[1])}):(c=nb.exec(a))?b=[B(c[1]),B(c[2]),B(c[3]),parseFloat(c[4],10)]:(c=ob.exec(a))?b=[B(c[1],16),B(c[2],16),B(c[3],16),1]:(c=pb.exec(a))&&(b=[B(c[1]),B(c[2]),B(c[3]),1])})(a);return{get:function(c){var f;
d?(f=E(a),f.stops=[].concat(f.stops),t(d,function(a,b){f.stops[b]=[f.stops[b][0],a.get(c)]})):f=b&&!isNaN(b[0])?"rgb"===c?"rgb("+b[0]+","+b[1]+","+b[2]+")":"a"===c?b[3]:"rgba("+b.join(",")+")":a;return f},brighten:function(a){if(d)t(d,function(b){b.brighten(a)});else if(U(a)&&0!==a){var c;for(c=0;3>c;c++)b[c]+=B(255*a),0>b[c]&&(b[c]=0),255<b[c]&&(b[c]=255)}return this},rgba:b,setOpacity:function(a){b[3]=a;return this}}};N.prototype={init:function(a,b){this.element="span"===b?ia(b):F.createElementNS("http://www.w3.org/2000/svg",
b);this.renderer=a},opacity:1,animate:function(a,b,c){b=k(b,da,!0);La(this);b?(b=E(b,{}),c&&(b.complete=c),fb(this,a,b)):(this.attr(a),c&&c())},colorGradient:function(a,b,c){var d=this.renderer,e,f,g,h,l,m,q,p,v,n,H=[];a.linearGradient?f="linearGradient":a.radialGradient&&(f="radialGradient");if(f){g=a[f];h=d.gradients;m=a.stops;v=c.radialReference;Y(g)&&(a[f]=g={x1:g[0],y1:g[1],x2:g[2],y2:g[3],gradientUnits:"userSpaceOnUse"});"radialGradient"===f&&v&&!u(g.gradientUnits)&&(g=E(g,{cx:v[0]-v[2]/2+g.cx*
v[2],cy:v[1]-v[2]/2+g.cy*v[2],r:g.r*v[2],gradientUnits:"userSpaceOnUse"}));for(n in g)"id"!==n&&H.push(n,g[n]);for(n in m)H.push(m[n]);H=H.join(",");h[H]?a=h[H].attr("id"):(g.id=a="highcharts-"+Ja++,h[H]=l=d.createElement(f).attr(g).add(d.defs),l.stops=[],t(m,function(a){0===a[1].indexOf("rgba")?(e=xa(a[1]),q=e.get("rgb"),p=e.get("a")):(q=a[1],p=1);a=d.createElement("stop").attr({offset:a[0],"stop-color":q,"stop-opacity":p}).add(l);l.stops.push(a)}));c.setAttribute(b,"url("+d.url+"#"+a+")")}},attr:function(a,
b){var c,d,e=this.element,f,g=this,h;"string"===typeof a&&b!==A&&(c=a,a={},a[c]=b);if("string"===typeof a)g=(this[a+"Getter"]||this._defaultGetter).call(this,a,e);else{for(c in a)d=a[c],h=!1,this.symbolName&&/^(x|y|width|height|r|start|end|innerR|anchorX|anchorY)/.test(c)&&(f||(this.symbolAttr(a),f=!0),h=!0),!this.rotation||"x"!==c&&"y"!==c||(this.doTransform=!0),h||(this[c+"Setter"]||this._defaultSetter).call(this,d,c,e),this.shadows&&/^(width|height|visibility|x|y|d|transform|cx|cy|r)$/.test(c)&&
this.updateShadows(c,d);this.doTransform&&(this.updateTransform(),this.doTransform=!1)}return g},updateShadows:function(a,b){for(var c=this.shadows,d=c.length;d--;)c[d].setAttribute(a,"height"===a?z(b-(c[d].cutHeight||0),0):"d"===a?this.d:b)},addClass:function(a){var b=this.element,c=G(b,"class")||"";-1===c.indexOf(a)&&G(b,"class",c+" "+a);return this},symbolAttr:function(a){var b=this;t("x y r start end width height innerR anchorX anchorY".split(" "),function(c){b[c]=k(a[c],b[c])});b.attr({d:b.renderer.symbols[b.symbolName](b.x,
b.y,b.width,b.height,b)})},clip:function(a){return this.attr("clip-path",a?"url("+this.renderer.url+"#"+a.id+")":aa)},crisp:function(a){var b,c={},d,e=a.strokeWidth||this.strokeWidth||this.attr&&this.attr("stroke-width")||0;d=C(e)%2/2;a.x=ca(a.x||this.x||0)+d;a.y=ca(a.y||this.y||0)+d;a.width=ca((a.width||this.width||0)-2*d);a.height=ca((a.height||this.height||0)-2*d);a.strokeWidth=e;for(b in a)this[b]!==a[b]&&(this[b]=c[b]=a[b]);return c},css:function(a){var b=this.styles,c={},d=this.element,e,f,
g="";e=!b;a&&a.color&&(a.fill=a.color);if(b)for(f in a)a[f]!==b[f]&&(c[f]=a[f],e=!0);if(e){e=this.textWidth=a&&a.width&&"text"===d.nodeName.toLowerCase()&&B(a.width);b&&(a=s(b,c));this.styles=a;e&&(ja||!$&&this.renderer.forExport)&&delete a.width;if(na&&!$)K(this.element,a);else{b=function(a,b){return"-"+b.toLowerCase()};for(f in a)g+=f.replace(/([A-Z])/g,b)+":"+a[f]+";";G(d,"style",g)}e&&this.added&&this.renderer.buildText(this)}return this},on:function(a,b){this.element["on"+a]=b;return this},setRadialReference:function(a){this.element.radialReference=
a;return this},translate:function(a,b){return this.attr({translateX:a,translateY:b})},invert:function(){this.inverted=!0;this.updateTransform();return this},updateTransform:function(){var a=this.translateX||0,b=this.translateY||0,c=this.scaleX,d=this.scaleY,e=this.inverted,f=this.rotation,g=this.element;e&&(a+=this.attr("width"),b+=this.attr("height"));a=["translate("+a+","+b+")"];e?a.push("rotate(90) scale(-1,1)"):f&&a.push("rotate("+f+" "+(g.getAttribute("x")||0)+" "+(g.getAttribute("y")||0)+")");
(u(c)||u(d))&&a.push("scale("+k(c,1)+" "+k(d,1)+")");a.length&&g.setAttribute("transform",a.join(" "))},toFront:function(){var a=this.element;a.parentNode.appendChild(a);return this},align:function(a,b,c){var d,e,f,g,h={};e=this.renderer;f=e.alignedObjects;if(a){if(this.alignOptions=a,this.alignByTranslate=b,!c||fa(c))this.alignTo=d=c||"renderer",T(f,this),f.push(this),c=null}else a=this.alignOptions,b=this.alignByTranslate,d=this.alignTo;c=k(c,e[d],e);d=a.align;e=a.verticalAlign;f=(c.x||0)+(a.x||
0);g=(c.y||0)+(a.y||0);if("right"===d||"center"===d)f+=(c.width-(a.width||0))/{right:1,center:2}[d];h[b?"translateX":"x"]=C(f);if("bottom"===e||"middle"===e)g+=(c.height-(a.height||0))/({bottom:1,middle:2}[e]||1);h[b?"translateY":"y"]=C(g);this[this.placed?"animate":"attr"](h);this.placed=!0;this.alignAttr=h;return this},getBBox:function(){var a=this.bBox,b=this.renderer,c,d,e=this.rotation;c=this.element;var f=this.styles,g=e*Za;d=this.textStr;var h;if(""===d||kb.test(d))h="num."+d.toString().length+
(f?"|"+f.fontSize+"|"+f.fontFamily:"");h&&(a=b.cache[h]);if(!a){if("http://www.w3.org/2000/svg"===c.namespaceURI||b.forExport){try{a=c.getBBox?s({},c.getBBox()):{width:c.offsetWidth,height:c.offsetHeight}}catch(l){}if(!a||0>a.width)a={width:0,height:0}}else a=this.htmlGetBBox();b.isSVG&&(c=a.width,d=a.height,na&&f&&"11px"===f.fontSize&&"16.9"===d.toPrecision(3)&&(a.height=d=14),e&&(a.width=la(d*Da(g))+la(c*va(g)),a.height=la(d*va(g))+la(c*Da(g))));this.bBox=a;h&&(b.cache[h]=a)}return a},show:function(a){return a&&
"http://www.w3.org/2000/svg"===this.element.namespaceURI?(this.element.removeAttribute("visibility"),this):this.attr({visibility:a?"inherit":"visible"})},hide:function(){return this.attr({visibility:"hidden"})},fadeOut:function(a){var b=this;b.animate({opacity:0},{duration:a||150,complete:function(){b.hide()}})},add:function(a){var b=this.renderer,c=a||b,d=c.element||b.box,e=this.element,f=this.zIndex,g,h;a&&(this.parentGroup=a);this.parentInverted=a&&a.inverted;void 0!==this.textStr&&b.buildText(this);
f&&(c.handleZ=!0,f=B(f));if(c.handleZ)for(a=d.childNodes,g=0;g<a.length;g++)if(b=a[g],c=G(b,"zIndex"),b!==e&&(B(c)>f||!u(f)&&u(c))){d.insertBefore(e,b);h=!0;break}h||d.appendChild(e);this.added=!0;if(this.onAdd)this.onAdd();return this},safeRemoveChild:function(a){var b=a.parentNode;b&&b.removeChild(a)},destroy:function(){var a=this,b=a.element||{},c=a.shadows,d=a.renderer.isSVG&&"SPAN"===b.nodeName&&a.parentGroup,e,f;b.onclick=b.onmouseout=b.onmouseover=b.onmousemove=b.point=null;La(a);a.clipPath&&
(a.clipPath=a.clipPath.destroy());if(a.stops){for(f=0;f<a.stops.length;f++)a.stops[f]=a.stops[f].destroy();a.stops=null}a.safeRemoveChild(b);for(c&&t(c,function(b){a.safeRemoveChild(b)});d&&0===d.div.childNodes.length;)b=d.parentGroup,a.safeRemoveChild(d.div),delete d.div,d=b;a.alignTo&&T(a.renderer.alignedObjects,a);for(e in a)delete a[e];return null},shadow:function(a,b,c){var d=[],e,f,g=this.element,h,l,m,q;if(a){l=k(a.width,3);m=(a.opacity||0.15)/l;q=this.parentInverted?"(-1,-1)":"("+k(a.offsetX,
1)+", "+k(a.offsetY,1)+")";for(e=1;e<=l;e++)f=g.cloneNode(0),h=2*l+1-2*e,G(f,{isShadow:"true",stroke:a.color||"black","stroke-opacity":m*e,"stroke-width":h,transform:"translate"+q,fill:aa}),c&&(G(f,"height",z(G(f,"height")-h,0)),f.cutHeight=h),b?b.element.appendChild(f):g.parentNode.insertBefore(f,g),d.push(f);this.shadows=d}return this},xGetter:function(a){"circle"===this.element.nodeName&&(a={x:"cx",y:"cy"}[a]||a);return this._defaultGetter(a)},_defaultGetter:function(a){a=k(this[a],this.element?
this.element.getAttribute(a):null,0);/^[0-9\.]+$/.test(a)&&(a=parseFloat(a));return a},dSetter:function(a,b,c){a&&a.join&&(a=a.join(" "));/(NaN| {2}|^$)/.test(a)&&(a="M 0 0");c.setAttribute(b,a);this[b]=a},dashstyleSetter:function(a){var b;if(a=a&&a.toLowerCase()){a=a.replace("shortdashdotdot","3,1,1,1,1,1,").replace("shortdashdot","3,1,1,1").replace("shortdot","1,1,").replace("shortdash","3,1,").replace("longdash","8,3,").replace(/dot/g,"1,3,").replace("dash","4,3,").replace(/,$/,"").split(",");
for(b=a.length;b--;)a[b]=B(a[b])*this.element.getAttribute("stroke-width");a=a.join(",");this.element.setAttribute("stroke-dasharray",a)}},alignSetter:function(a){this.element.setAttribute("text-anchor",{left:"start",center:"middle",right:"end"}[a])},opacitySetter:function(a,b,c){this[b]=a;c.setAttribute(b,a)},"stroke-widthSetter":function(a,b,c){0===a&&(a=1E-5);this.strokeWidth=a;c.setAttribute(b,a)},titleSetter:function(a){var b=this.element.getElementsByTagName("title")[0];b||(b=F.createElementNS("http://www.w3.org/2000/svg",
"title"),this.element.appendChild(b));b.textContent=a},textSetter:function(a){a!==this.textStr&&(delete this.bBox,this.textStr=a,this.added&&this.renderer.buildText(this))},fillSetter:function(a,b,c){"string"===typeof a?c.setAttribute(b,a):a&&this.colorGradient(a,b,c)},zIndexSetter:function(a,b,c){c.setAttribute(b,a);this[b]=a},_defaultSetter:function(a,b,c){c.setAttribute(b,a)}};N.prototype.yGetter=N.prototype.xGetter;N.prototype.translateXSetter=N.prototype.translateYSetter=N.prototype.rotationSetter=
N.prototype.verticalAlignSetter=N.prototype.scaleXSetter=N.prototype.scaleYSetter=function(a,b){this[b]=a;this.doTransform=!0};var ya=function(){this.init.apply(this,arguments)};ya.prototype={Element:N,init:function(a,b,c,d,e){var f=location,g;d=this.createElement("svg").attr({version:"1.1"}).css(this.getStyle(d));g=d.element;a.appendChild(g);-1===a.innerHTML.indexOf("xmlns")&&G(g,"xmlns","http://www.w3.org/2000/svg");this.isSVG=!0;this.box=g;this.boxWrapper=d;this.alignedObjects=[];this.url=(Ea||
$a)&&F.getElementsByTagName("base").length?f.href.replace(/#.*?$/,"").replace(/([\('\)])/g,"\\$1").replace(/ /g,"%20"):"";this.createElement("desc").add().element.appendChild(F.createTextNode("Created with @product.name@ @product.version@"));this.defs=this.createElement("defs").add();this.forExport=e;this.gradients={};this.cache={};this.setSize(b,c,!1);var h;Ea&&a.getBoundingClientRect&&(this.subPixelFix=b=function(){K(a,{left:0,top:0});h=a.getBoundingClientRect();K(a,{left:ta(h.left)-h.left+"px",
top:ta(h.top)-h.top+"px"})},b(),V(M,"resize",b))},getStyle:function(a){return this.style=s({fontFamily:'"Lucida Grande", "Lucida Sans Unicode", Arial, Helvetica, sans-serif',fontSize:"12px"},a)},isHidden:function(){return!this.boxWrapper.getBBox().width},destroy:function(){var a=this.defs;this.box=null;this.boxWrapper=this.boxWrapper.destroy();pa(this.gradients||{});this.gradients=null;a&&(this.defs=a.destroy());this.subPixelFix&&ea(M,"resize",this.subPixelFix);return this.alignedObjects=null},createElement:function(a){var b=
new this.Element;b.init(this,a);return b},draw:function(){},buildText:function(a){for(var b=a.element,c=this,d=c.forExport,e=k(a.textStr,"").toString(),f=-1!==e.indexOf("<"),g=b.childNodes,h,l,m=G(b,"x"),q=a.styles,p=a.textWidth,v=q&&q.lineHeight,n=g.length,H=function(a){return v?B(v):c.fontMetrics(/(px|em)$/.test(a&&a.style.fontSize)?a.style.fontSize:q&&q.fontSize||c.style.fontSize||12).h};n--;)b.removeChild(g[n]);f||-1!==e.indexOf(" ")?(h=/<.*style="([^"]+)".*>/,l=/<.*href="(http[^"]+)".*>/,p&&
!a.added&&this.box.appendChild(b),e=f?e.replace(/<(b|strong)>/g,'<span style="font-weight:bold">').replace(/<(i|em)>/g,'<span style="font-style:italic">').replace(/<a/g,"<span").replace(/<\/(b|strong|i|em|a)>/g,"</span>").split(/<br.*?>/g):[e],""===e[e.length-1]&&e.pop(),t(e,function(e,f){var g,n=0;e=e.replace(/<span/g,"|||<span").replace(/<\/span>/g,"</span>|||");g=e.split("|||");t(g,function(e){if(""!==e||1===g.length){var v={},k=F.createElementNS("http://www.w3.org/2000/svg","tspan"),t;h.test(e)&&
(t=e.match(h)[1].replace(/(;| |^)color([ :])/,"$1fill$2"),G(k,"style",t));l.test(e)&&!d&&(G(k,"onclick",'location.href="'+e.match(l)[1]+'"'),K(k,{cursor:"pointer"}));e=(e.replace(/<(.|\n)*?>/g,"")||" ").replace(/&lt;/g,"<").replace(/&gt;/g,">");if(" "!==e&&(k.appendChild(F.createTextNode(e)),n?v.dx=0:f&&null!==m&&(v.x=m),G(k,v),!n&&f&&(!$&&d&&K(k,{display:"block"}),G(k,"dy",H(k),$a&&k.offsetHeight)),b.appendChild(k),n++,p)){e=e.replace(/([^\^])-/g,"$1- ").split(" ");for(var v=1<e.length&&"nowrap"!==
q.whiteSpace,r,x,gb=a._clipHeight,u=[],y=H(),s=1;v&&(e.length||u.length);)delete a.bBox,r=a.getBBox(),x=r.width,!$&&c.forExport&&(x=c.measureSpanWidth(k.firstChild.data,a.styles)),(r=x>p)&&1!==e.length?(k.removeChild(k.firstChild),u.unshift(e.pop())):(e=u,u=[],e.length&&(s++,gb&&s*y>gb?(e=["..."],a.attr("title",a.textStr)):(k=F.createElementNS("http://www.w3.org/2000/svg","tspan"),G(k,{dy:y,x:m}),t&&G(k,"style",t),b.appendChild(k),x>p&&(p=x)))),e.length&&k.appendChild(F.createTextNode(e.join(" ").replace(/- /g,
"-")))}}})})):b.appendChild(F.createTextNode(e))},button:function(a,b,c,d,e,f,g,h,l){var m=this.label(a,b,c,l,null,null,null,null,"button"),q=0,p,v,n,H,k,t;a={x1:0,y1:0,x2:0,y2:1};e=E({"stroke-width":1,stroke:"#CCCCCC",fill:{linearGradient:a,stops:[[0,"#FEFEFE"],[1,"#F6F6F6"]]},r:2,padding:5,style:{color:"black"}},e);n=e.style;delete e.style;f=E(e,{stroke:"#68A",fill:{linearGradient:a,stops:[[0,"#FFF"],[1,"#ACF"]]}},f);H=f.style;delete f.style;g=E(e,{stroke:"#68A",fill:{linearGradient:a,stops:[[0,
"#9BD"],[1,"#CDF"]]}},g);k=g.style;delete g.style;h=E(e,{style:{color:"#CCC"}},h);t=h.style;delete h.style;V(m.element,na?"mouseover":"mouseenter",function(){3!==q&&m.attr(f).css(H)});V(m.element,na?"mouseout":"mouseleave",function(){3!==q&&(p=[e,f,g][q],v=[n,H,k][q],m.attr(p).css(v))});m.setState=function(a){(m.state=q=a)?2===a?m.attr(g).css(k):3===a&&m.attr(h).css(t):m.attr(e).css(n)};return m.on("click",function(){3!==q&&d.call(m)}).attr(e).css(s({cursor:"default"},n))},crispLine:function(a,b){a[1]===
a[4]&&(a[1]=a[4]=C(a[1])-b%2/2);a[2]===a[5]&&(a[2]=a[5]=C(a[2])+b%2/2);return a},path:function(a){var b={fill:aa};Y(a)?b.d=a:J(a)&&s(b,a);return this.createElement("path").attr(b)},circle:function(a,b,c){a=J(a)?a:{x:a,y:b,r:c};b=this.createElement("circle");b.xSetter=function(a){this.element.setAttribute("cx",a)};b.ySetter=function(a){this.element.setAttribute("cy",a)};return b.attr(a)},arc:function(a,b,c,d,e,f){J(a)&&(b=a.y,c=a.r,d=a.innerR,e=a.start,f=a.end,a=a.x);a=this.symbol("arc",a||0,b||0,
c||0,c||0,{innerR:d||0,start:e||0,end:f||0});a.r=c;return a},rect:function(a,b,c,d,e,f){e=J(a)?a.r:e;var g=this.createElement("rect");a=J(a)?a:a===A?{}:{x:a,y:b,width:z(c,0),height:z(d,0)};f!==A&&(a.strokeWidth=f,a=g.crisp(a));e&&(a.r=e);g.rSetter=function(a){G(this.element,{rx:a,ry:a})};return g.attr(a)},setSize:function(a,b,c){var d=this.alignedObjects,e=d.length;this.width=a;this.height=b;for(this.boxWrapper[k(c,!0)?"animate":"attr"]({width:a,height:b});e--;)d[e].align()},g:function(a){var b=this.createElement("g");
return u(a)?b.attr({"class":"highcharts-"+a}):b},image:function(a,b,c,d,e){var f={preserveAspectRatio:aa};1<arguments.length&&s(f,{x:b,y:c,width:d,height:e});f=this.createElement("image").attr(f);f.element.setAttributeNS?f.element.setAttributeNS("http://www.w3.org/1999/xlink","href",a):f.element.setAttribute("hc-svg-href",a);return f},symbol:function(a,b,c,d,e,f){var g,h=this.symbols[a],h=h&&h(C(b),C(c),d,e,f),l=/^url\((.*?)\)$/,m,q;h?(g=this.path(h),s(g,{symbolName:a,x:b,y:c,width:d,height:e}),f&&
s(g,f)):l.test(a)&&(q=function(a,b){a.element&&(a.attr({width:b[0],height:b[1]}),a.alignByTranslate||a.translate(C((d-b[0])/2),C((e-b[1])/2)))},m=a.match(l)[1],a=bb[m],g=this.image(m).attr({x:b,y:c}),g.isImg=!0,a?q(g,a):(g.attr({width:0,height:0}),ia("img",{onload:function(){q(g,bb[m]=[this.width,this.height])},src:m})));return g},symbols:{circle:function(a,b,c,d){var e=0.166*c;return["M",a+c/2,b,"C",a+c+e,b,a+c+e,b+d,a+c/2,b+d,"C",a-e,b+d,a-e,b,a+c/2,b,"Z"]},square:function(a,b,c,d){return["M",a,
b,"L",a+c,b,a+c,b+d,a,b+d,"Z"]},triangle:function(a,b,c,d){return["M",a+c/2,b,"L",a+c,b+d,a,b+d,"Z"]},"triangle-down":function(a,b,c,d){return["M",a,b,"L",a+c,b,a+c/2,b+d,"Z"]},diamond:function(a,b,c,d){return["M",a+c/2,b,"L",a+c,b+d/2,a+c/2,b+d,a,b+d/2,"Z"]},arc:function(a,b,c,d,e){var f=e.start;c=e.r||c||d;var g=e.end-0.001;d=e.innerR;var h=e.open,l=va(f),m=Da(f),q=va(g),g=Da(g);e=e.end-f<Ya?0:1;return["M",a+c*l,b+c*m,"A",c,c,0,e,1,a+c*q,b+c*g,h?"M":"L",a+d*q,b+d*g,"A",d,d,0,e,0,a+d*l,b+d*m,h?"":
"Z"]},callout:function(a,b,c,d,e){var f=ga(e&&e.r||0,c,d),g=f+6,h=e&&e.anchorX,l=e&&e.anchorY;e=C(e.strokeWidth||0)%2/2;a+=e;b+=e;e=["M",a+f,b,"L",a+c-f,b,"C",a+c,b,a+c,b,a+c,b+f,"L",a+c,b+d-f,"C",a+c,b+d,a+c,b+d,a+c-f,b+d,"L",a+f,b+d,"C",a,b+d,a,b+d,a,b+d-f,"L",a,b+f,"C",a,b,a,b,a+f,b];h&&h>c&&l>b+g&&l<b+d-g?e.splice(13,3,"L",a+c,l-6,a+c+6,l,a+c,l+6,a+c,b+d-f):h&&0>h&&l>b+g&&l<b+d-g?e.splice(33,3,"L",a,l+6,a-6,l,a,l-6,a,b+f):l&&l>d&&h>a+g&&h<a+c-g?e.splice(23,3,"L",h+6,b+d,h,b+d+6,h-6,b+d,a+f,b+
d):l&&0>l&&h>a+g&&h<a+c-g&&e.splice(3,3,"L",h-6,b,h,b-6,h+6,b,c-f,b);return e}},clipRect:function(a,b,c,d){var e="highcharts-"+Ja++,f=this.createElement("clipPath").attr({id:e}).add(this.defs);a=this.rect(a,b,c,d,0).add(f);a.id=e;a.clipPath=f;return a},text:function(a,b,c,d){var e=ja||!$&&this.forExport,f={};if(d&&!this.forExport)return this.html(a,b,c);f.x=Math.round(b||0);c&&(f.y=Math.round(c));if(a||0===a)f.text=a;a=this.createElement("text").attr(f);e&&a.css({position:"absolute"});d||(a.xSetter=
function(a,b,c){var d=c.childNodes,e,f;for(f=1;f<d.length;f++)e=d[f],e.getAttribute("x")===c.getAttribute("x")&&e.setAttribute("x",a);c.setAttribute(b,a)});return a},fontMetrics:function(a){a=a||this.style.fontSize;a=/px/.test(a)?B(a):/em/.test(a)?12*parseFloat(a):12;a=24>a?a+4:C(1.2*a);var b=C(0.8*a);return{h:a,b:b}},label:function(a,b,c,d,e,f,g,h,l){function m(){var a,b;a=k.element.style;x=(void 0===z||void 0===F||n.styles.textAlign)&&k.textStr&&k.getBBox();n.width=(z||x.width||0)+2*w+L;n.height=
(F||x.height||0)+2*w;I=w+v.fontMetrics(a&&a.fontSize).b;M&&(r||(a=C(-y*w),b=h?-I:0,n.box=r=d?v.symbol(d,a,b,n.width,n.height,X):v.rect(a,b,n.width,n.height,0,X[lb]),r.attr("fill",aa).add(n)),r.isImg||r.attr(s({width:C(n.width),height:C(n.height)},X)),X=null)}function q(){var a=n.styles,a=a&&a.textAlign,b=L+w*(1-y),c;c=h?0:I;u(z)&&x&&("center"===a||"right"===a)&&(b+={center:0.5,right:1}[a]*(z-x.width));if(b!==k.x||c!==k.y)k.attr("x",b),c!==A&&k.attr("y",c);k.x=b;k.y=c}function p(a,b){r?r.attr(a,b):
X[a]=b}var v=this,n=v.g(l),k=v.text("",0,0,g).attr({zIndex:1}),r,x,y=0,w=3,L=0,z,F,B,D,G=0,X={},I,M;n.onAdd=function(){k.add(n);n.attr({text:a||"",x:b,y:c});r&&u(e)&&n.attr({anchorX:e,anchorY:f})};n.widthSetter=function(a){z=a};n.heightSetter=function(a){F=a};n.paddingSetter=function(a){u(a)&&a!==w&&(w=a,q())};n.paddingLeftSetter=function(a){u(a)&&a!==L&&(L=a,q())};n.alignSetter=function(a){y={left:0,center:0.5,right:1}[a]};n.textSetter=function(a){a!==A&&k.textSetter(a);m();q()};n["stroke-widthSetter"]=
function(a,b){a&&(M=!0);G=a%2/2;p(b,a)};n.strokeSetter=n.fillSetter=n.rSetter=function(a,b){"fill"===b&&a&&(M=!0);p(b,a)};n.anchorXSetter=function(a,b){e=a;p(b,a+G-B)};n.anchorYSetter=function(a,b){f=a;p(b,a-D)};n.xSetter=function(a){n.x=a;y&&(a-=y*((z||x.width)+w));B=C(a);n.attr("translateX",B)};n.ySetter=function(a){D=n.y=C(a);n.attr("translateY",D)};var Aa=n.css;return s(n,{css:function(a){if(a){var b={};a=E(a);t("fontSize fontWeight fontFamily color lineHeight width textDecoration textShadow".split(" "),
function(c){a[c]!==A&&(b[c]=a[c],delete a[c])});k.css(b)}return Aa.call(n,a)},getBBox:function(){return{width:x.width+2*w,height:x.height+2*w,x:x.x-w,y:x.y-w}},shadow:function(a){r&&r.shadow(a);return n},destroy:function(){ea(n.element,"mouseenter");ea(n.element,"mouseleave");k&&(k=k.destroy());r&&(r=r.destroy());N.prototype.destroy.call(n);n=v=m=q=p=null}})}};ba.prototype={addLabel:function(){var a=this.axis,b=a.options,c=a.chart,d=a.horiz,e=a.categories,f=a.names,g=this.pos,h=b.labels,l=a.tickPositions,
d=d&&e&&!h.step&&!h.staggerLines&&!h.rotation&&c.plotWidth/l.length||!d&&(c.margin[3]||0.33*c.chartWidth),m=g===l[0],q=g===l[l.length-1],p,f=e?k(e[g],f[g],g):g,e=this.label,v=l.info;a.isDatetimeAxis&&v&&(p=b.dateTimeLabelFormats[v.higherRanks[g]||v.unitName]);this.isFirst=m;this.isLast=q;b=a.labelFormatter.call({axis:a,chart:c,isFirst:m,isLast:q,dateTimeLabelFormat:p,value:a.isLog?Z(O(f)):f});g=d&&{width:z(1,C(d-2*(h.padding||10)))+"px"};g=s(g,h.style);u(e)?e&&e.attr({text:b}).css(g):(p={align:a.labelAlign},
U(h.rotation)&&(p.rotation=h.rotation),d&&h.ellipsis&&(p._clipHeight=a.len/l.length),this.label=u(b)&&h.enabled?c.renderer.text(b,0,0,h.useHTML).attr(p).css(g).add(a.labelGroup):null)},getLabelSize:function(){var a=this.label,b=this.axis;return a?a.getBBox()[b.horiz?"height":"width"]:0},getLabelSides:function(){var a=this.label.getBBox(),b=this.axis,c=b.horiz,d=b.options.labels,a=c?a.width:a.height,b=c?d.x-a*{left:0,center:0.5,right:1}[b.labelAlign]:0;return[b,c?a+b:a]},handleOverflow:function(a,
b){var c=!0,d=this.axis,e=this.isFirst,f=this.isLast,g=d.horiz?b.x:b.y,h=d.reversed,l=d.tickPositions,m=this.getLabelSides(),q=m[0],m=m[1],p,v,n,k=this.label.line||0;p=d.labelEdge;v=d.justifyLabels&&(e||f);p[k]===A||g+q>p[k]?p[k]=g+m:v||(c=!1);if(v){p=(v=d.justifyToPlot)?d.pos:0;v=v?p+d.len:d.chart.chartWidth;do a+=e?1:-1,n=d.ticks[l[a]];while(l[a]&&(!n||n.label.line!==k));d=n&&n.label.xy&&n.label.xy.x+n.getLabelSides()[e?0:1];e&&!h||f&&h?g+q<p&&(g=p-q,n&&g+m>d&&(c=!1)):g+m>v&&(g=v-m,n&&g+q<d&&(c=
!1));b.x=g}return c},getPosition:function(a,b,c,d){var e=this.axis,f=e.chart,g=d&&f.oldChartHeight||f.chartHeight;return{x:a?e.translate(b+c,null,null,d)+e.transB:e.left+e.offset+(e.opposite?(d&&f.oldChartWidth||f.chartWidth)-e.right-e.left:0),y:a?g-e.bottom+e.offset-(e.opposite?e.height:0):g-e.translate(b+c,null,null,d)-e.transB}},getLabelPosition:function(a,b,c,d,e,f,g,h){var l=this.axis,m=l.transA,q=l.reversed,p=l.staggerLines,v=l.chart.renderer.fontMetrics(e.style.fontSize).b,n=e.rotation;a=a+
e.x-(f&&d?f*m*(q?-1:1):0);b=b+e.y-(f&&!d?f*m*(q?1:-1):0);n&&2===l.side&&(b-=v-v*va(n*Za));u(e.y)||n||(b+=v-c.getBBox().height/2);p&&(c.line=g/(h||1)%p,b+=l.labelOffset/p*c.line);return{x:a,y:b}},getMarkPath:function(a,b,c,d,e,f){return f.crispLine(["M",a,b,"L",a+(e?0:-c),b+(e?c:0)],d)},render:function(a,b,c){var d=this.axis,e=d.options,f=d.chart.renderer,g=d.horiz,h=this.type,l=this.label,m=this.pos,q=e.labels,p=this.gridLine,v=h?h+"Grid":"grid",n=h?h+"Tick":"tick",H=e[v+"LineWidth"],r=e[v+"LineColor"],
t=e[v+"LineDashStyle"],x=e[n+"Length"],v=e[n+"Width"]||0,y=e[n+"Color"],u=e[n+"Position"],n=this.mark,w=q.step,s=!0,L=d.tickmarkOffset,z=this.getPosition(g,m,L,b),F=z.x,z=z.y,X=g&&F===d.pos+d.len||!g&&z===d.pos?-1:1;this.isActive=!0;if(H&&(m=d.getPlotLinePath(m+L,H*X,b,!0),p===A&&(p={stroke:r,"stroke-width":H},t&&(p.dashstyle=t),h||(p.zIndex=1),b&&(p.opacity=0),this.gridLine=p=H?f.path(m).attr(p).add(d.gridGroup):null),!b&&p&&m))p[this.isNew?"attr":"animate"]({d:m,opacity:c});v&&x&&("inside"===u&&
(x=-x),d.opposite&&(x=-x),h=this.getMarkPath(F,z,x,v*X,g,f),n?n.animate({d:h,opacity:c}):this.mark=f.path(h).attr({stroke:y,"stroke-width":v,opacity:c}).add(d.axisGroup));l&&!isNaN(F)&&(l.xy=z=this.getLabelPosition(F,z,l,g,q,L,a,w),this.isFirst&&!this.isLast&&!k(e.showFirstLabel,1)||this.isLast&&!this.isFirst&&!k(e.showLastLabel,1)?s=!1:d.isRadial||q.step||q.rotation||b||0===c||(s=this.handleOverflow(a,z)),w&&a%w&&(s=!1),s&&!isNaN(z.y)?(z.opacity=c,l[this.isNew?"attr":"animate"](z),this.isNew=!1):
l.attr("y",-9999))},destroy:function(){pa(this,this.axis)}};Ca.prototype={defaultOptions:{dateTimeLabelFormats:{millisecond:"%H:%M:%S.%L",second:"%H:%M:%S",minute:"%H:%M",hour:"%H:%M",day:"%e. %b",week:"%e. %b",month:"%b '%y",year:"%Y"},endOnTick:!1,gridLineColor:"#C0C0C0",labels:Ma,lineColor:"#C0D0E0",lineWidth:1,minPadding:0.01,maxPadding:0.01,minorGridLineColor:"#E0E0E0",minorGridLineWidth:1,minorTickColor:"#A0A0A0",minorTickLength:2,minorTickPosition:"outside",startOfWeek:1,startOnTick:!1,tickColor:"#C0D0E0",
tickLength:10,tickmarkPlacement:"between",tickPixelInterval:100,tickPosition:"outside",tickWidth:1,title:{align:"middle",style:{color:"#707070"}},type:"linear"},defaultYAxisOptions:{endOnTick:!0,gridLineWidth:1,tickPixelInterval:72,showLastLabel:!0,labels:{x:-8,y:3},lineWidth:0,maxPadding:0.05,minPadding:0.05,startOnTick:!0,tickWidth:0,title:{rotation:270,text:"Values"},stackLabels:{enabled:!1,formatter:function(){return x(this.total,-1)},style:Ma.style}},defaultLeftAxisOptions:{labels:{x:-15,y:null},
title:{rotation:270}},defaultRightAxisOptions:{labels:{x:15,y:null},title:{rotation:90}},defaultBottomAxisOptions:{labels:{x:0,y:20},title:{rotation:0}},defaultTopAxisOptions:{labels:{x:0,y:-15},title:{rotation:0}},init:function(a,b){var c=b.isX;this.horiz=a.inverted?!c:c;this.coll=(this.isXAxis=c)?"xAxis":"yAxis";this.opposite=b.opposite;this.side=b.side||(this.horiz?this.opposite?0:2:this.opposite?1:3);this.setOptions(b);var d=this.options,e=d.type;this.labelFormatter=d.labels.formatter||this.defaultLabelFormatter;
this.userOptions=b;this.minPixelPadding=0;this.chart=a;this.reversed=d.reversed;this.zoomEnabled=!1!==d.zoomEnabled;this.categories=d.categories||"category"===e;this.names=[];this.isLog="logarithmic"===e;this.isDatetimeAxis="datetime"===e;this.isLinked=u(d.linkedTo);this.tickmarkOffset=this.categories&&"between"===d.tickmarkPlacement?0.5:0;this.ticks={};this.labelEdge=[];this.minorTicks={};this.plotLinesAndBands=[];this.alternateBands={};this.len=0;this.minRange=this.userMinRange=d.minRange||d.maxZoom;
this.range=d.range;this.offset=d.offset||0;this.stacks={};this.oldStacks={};this.min=this.max=null;this.crosshair=k(d.crosshair,ka(a.options.tooltip.crosshairs)[c?0:1],!1);var f,d=this.options.events;-1===mb(this,a.axes)&&(c&&!this.isColorAxis?a.axes.splice(a.xAxis.length,0,this):a.axes.push(this),a[this.coll].push(this));this.series=this.series||[];a.inverted&&c&&this.reversed===A&&(this.reversed=!0);this.removePlotLine=this.removePlotBand=this.removePlotBandOrLine;for(f in d)V(this,f,d[f]);this.isLog&&
(this.val2lin=R,this.lin2val=O)},setOptions:function(a){this.options=E(this.defaultOptions,this.isXAxis?{}:this.defaultYAxisOptions,[this.defaultTopAxisOptions,this.defaultRightAxisOptions,this.defaultBottomAxisOptions,this.defaultLeftAxisOptions][this.side],E(Q[this.coll],a))},defaultLabelFormatter:function(){var a=this.axis,b=this.value,c=a.categories,d=this.dateTimeLabelFormat,e=Q.lang.numericSymbols,f=e&&e.length,g,h=a.options.labels.format,a=a.isLog?b:a.tickInterval;if(h)g=y(h,this);else if(c)g=
b;else if(d)g=za(d,b);else if(f&&1E3<=a)for(;f--&&g===A;)c=Math.pow(1E3,f+1),a>=c&&null!==e[f]&&(g=x(b/c,-1)+e[f]);g===A&&(g=1E4<=b?x(b,0):x(b,-1,A,""));return g},getSeriesExtremes:function(){var a=this,b=a.chart;a.hasVisibleSeries=!1;a.dataMin=a.dataMax=null;a.buildStacks&&a.buildStacks();t(a.series,function(c){if(c.visible||!b.options.chart.ignoreHiddenSeries){var d;d=c.options.threshold;var e;a.hasVisibleSeries=!0;a.isLog&&0>=d&&(d=null);a.isXAxis?(d=c.xData,d.length&&(a.dataMin=ga(k(a.dataMin,
d[0]),w(d)),a.dataMax=z(k(a.dataMax,d[0]),ua(d)))):(c.getExtremes(),e=c.dataMax,c=c.dataMin,u(c)&&u(e)&&(a.dataMin=ga(k(a.dataMin,c),c),a.dataMax=z(k(a.dataMax,e),e)),u(d)&&(a.dataMin>=d?(a.dataMin=d,a.ignoreMinPadding=!0):a.dataMax<d&&(a.dataMax=d,a.ignoreMaxPadding=!0)))}})},translate:function(a,b,c,d,e,f){var g=1,h=0,l=d?this.oldTransA:this.transA;d=d?this.oldMin:this.min;var m=this.minPixelPadding;e=(this.options.ordinal||this.isLog&&e)&&this.lin2val;l||(l=this.transA);c&&(g*=-1,h=this.len);this.reversed&&
(g*=-1,h-=g*(this.sector||this.len));b?(a=a*g+h-m,a=a/l+d,e&&(a=this.lin2val(a))):(e&&(a=this.val2lin(a)),"between"===f&&(f=0.5),a=g*(a-d)*l+h+g*m+(U(f)?l*f*this.pointRange:0));return a},toPixels:function(a,b){return this.translate(a,!1,!this.horiz,null,!0)+(b?0:this.pos)},toValue:function(a,b){return this.translate(a-(b?0:this.pos),!0,!this.horiz,null,!0)},getPlotLinePath:function(a,b,c,d,e){var f=this.chart,g=this.left,h=this.top,l,m,q=c&&f.oldChartHeight||f.chartHeight,p=c&&f.oldChartWidth||f.chartWidth,
v;l=this.transB;e=k(e,this.translate(a,null,null,c));a=c=C(e+l);l=m=C(q-e-l);if(isNaN(e))v=!0;else if(this.horiz){if(l=h,m=q-this.bottom,a<g||a>g+this.width)v=!0}else if(a=g,c=p-this.right,l<h||l>h+this.height)v=!0;return v&&!d?null:f.renderer.crispLine(["M",a,l,"L",c,m],b||1)},getLinearTickPositions:function(a,b,c){var d,e=Z(ca(b/a)*a),f=Z(ta(c/a)*a),g=[];if(b===c&&U(b))return[b];for(b=e;b<=f;){g.push(b);b=Z(b+a);if(b===d)break;d=b}return g},getMinorTickPositions:function(){var a=this.options,b=
this.tickPositions,c=this.minorTickInterval,d=[],e;if(this.isLog)for(e=b.length,a=1;a<e;a++)d=d.concat(this.getLogTickPositions(c,b[a-1],b[a],!0));else if(this.isDatetimeAxis&&"auto"===a.minorTickInterval)d=d.concat(this.getTimeTicks(this.normalizeTimeTickInterval(c),this.min,this.max,a.startOfWeek)),d[0]<this.min&&d.shift();else for(b=this.min+(b[0]-this.min)%c;b<=this.max;b+=c)d.push(b);return d},adjustForMinRange:function(){var a=this.options,b=this.min,c=this.max,d,e=this.dataMax-this.dataMin>=
this.minRange,f,g,h,l,m;this.isXAxis&&this.minRange===A&&!this.isLog&&(u(a.min)||u(a.max)?this.minRange=null:(t(this.series,function(a){l=a.xData;for(g=m=a.xIncrement?1:l.length-1;0<g;g--)if(h=l[g]-l[g-1],f===A||h<f)f=h}),this.minRange=ga(5*f,this.dataMax-this.dataMin)));if(c-b<this.minRange){var q=this.minRange;d=(q-c+b)/2;d=[b-d,k(a.min,b-d)];e&&(d[2]=this.dataMin);b=ua(d);c=[b+q,k(a.max,b+q)];e&&(c[2]=this.dataMax);c=w(c);c-b<q&&(d[0]=c-q,d[1]=k(a.min,c-q),b=ua(d))}this.min=b;this.max=c},setAxisTranslation:function(a){var b=
this,c=b.max-b.min,d=b.axisPointRange||0,e,f=0,g=0,h=b.linkedParent,l=!!b.categories,m=b.transA;if(b.isXAxis||l||d)h?(f=h.minPointOffset,g=h.pointRangePadding):t(b.series,function(a){var h=l?1:b.isXAxis?a.pointRange:b.axisPointRange||0,m=a.options.pointPlacement,n=a.closestPointRange;h>c&&(h=0);d=z(d,h);f=z(f,fa(m)?0:h/2);g=z(g,"on"===m?0:h);!a.noSharedTooltip&&u(n)&&(e=u(e)?ga(e,n):n)}),h=b.ordinalSlope&&e?b.ordinalSlope/e:1,b.minPointOffset=f*=h,b.pointRangePadding=g*=h,b.pointRange=ga(d,c),b.closestPointRange=
e;a&&(b.oldTransA=m);b.translationSlope=b.transA=m=b.len/(c+g||1);b.transB=b.horiz?b.left:b.bottom;b.minPixelPadding=m*f},setTickPositions:function(a){var b=this,c=b.chart,d=b.options,e=b.isLog,f=b.isDatetimeAxis,g=b.isXAxis,h=b.isLinked,l=b.options.tickPositioner,m=d.maxPadding,q=d.minPadding,p=d.tickInterval,v=d.minTickInterval,n=d.tickPixelInterval,H,x=b.categories;h?(b.linkedParent=c[b.coll][d.linkedTo],c=b.linkedParent.getExtremes(),b.min=k(c.min,c.dataMin),b.max=k(c.max,c.dataMax),d.type!==
b.linkedParent.options.type&&I(11,1)):(b.min=k(b.userMin,d.min,b.dataMin),b.max=k(b.userMax,d.max,b.dataMax));e&&(!a&&0>=ga(b.min,k(b.dataMin,b.min))&&I(10,1),b.min=Z(R(b.min)),b.max=Z(R(b.max)));b.range&&u(b.max)&&(b.userMin=b.min=z(b.min,b.max-b.range),b.userMax=b.max,b.range=null);b.beforePadding&&b.beforePadding();b.adjustForMinRange();!(x||b.axisPointRange||b.usePercentage||h)&&u(b.min)&&u(b.max)&&(c=b.max-b.min)&&(u(d.min)||u(b.userMin)||!q||!(0>b.dataMin)&&b.ignoreMinPadding||(b.min-=c*q),
u(d.max)||u(b.userMax)||!m||!(0<b.dataMax)&&b.ignoreMaxPadding||(b.max+=c*m));U(d.floor)&&(b.min=z(b.min,d.floor));U(d.ceiling)&&(b.max=ga(b.max,d.ceiling));b.min===b.max||void 0===b.min||void 0===b.max?b.tickInterval=1:h&&!p&&n===b.linkedParent.options.tickPixelInterval?b.tickInterval=b.linkedParent.tickInterval:(b.tickInterval=k(p,x?1:(b.max-b.min)*n/z(b.len,n)),!u(p)&&b.len<n&&!this.isRadial&&!this.isLog&&!x&&d.startOnTick&&d.endOnTick&&(H=!0,b.tickInterval/=4));g&&!a&&t(b.series,function(a){a.processData(b.min!==
b.oldMin||b.max!==b.oldMax)});b.setAxisTranslation(!0);b.beforeSetTickPositions&&b.beforeSetTickPositions();b.postProcessTickInterval&&(b.tickInterval=b.postProcessTickInterval(b.tickInterval));b.pointRange&&(b.tickInterval=z(b.pointRange,b.tickInterval));!p&&b.tickInterval<v&&(b.tickInterval=v);f||e||p||(b.tickInterval=hb(b.tickInterval,null,S.pow(10,ca(S.log(b.tickInterval)/S.LN10)),d));b.minorTickInterval="auto"===d.minorTickInterval&&b.tickInterval?b.tickInterval/5:d.minorTickInterval;b.tickPositions=
a=d.tickPositions?[].concat(d.tickPositions):l&&l.apply(b,[b.min,b.max]);a||(!b.ordinalPositions&&(b.max-b.min)/b.tickInterval>z(2*b.len,200)&&I(19,!0),a=f?b.getTimeTicks(b.normalizeTimeTickInterval(b.tickInterval,d.units),b.min,b.max,d.startOfWeek,b.ordinalPositions,b.closestPointRange,!0):e?b.getLogTickPositions(b.tickInterval,b.min,b.max):b.getLinearTickPositions(b.tickInterval,b.min,b.max),H&&a.splice(1,a.length-2),b.tickPositions=a);h||(e=a[0],f=a[a.length-1],h=b.minPointOffset||0,d.startOnTick?
b.min=e:b.min-h>e&&a.shift(),d.endOnTick?b.max=f:b.max+h<f&&a.pop(),1===a.length&&(d=1E13<la(b.max)?1:0.001,b.min-=d,b.max+=d))},setMaxTicks:function(){var a=this.chart,b=a.maxTicks||{},c=this.tickPositions,d=this._maxTicksKey=[this.coll,this.pos,this.len].join("-");!this.isLinked&&!this.isDatetimeAxis&&c&&c.length>(b[d]||0)&&!1!==this.options.alignTicks&&(b[d]=c.length);a.maxTicks=b},adjustTickAmount:function(){var a=this._maxTicksKey,b=this.tickPositions,c=this.chart.maxTicks;if(c&&c[a]&&!this.isDatetimeAxis&&
!this.categories&&!this.isLinked&&!1!==this.options.alignTicks&&this.min!==A){var d=this.tickAmount,e=b.length;this.tickAmount=a=c[a];if(e<a){for(;b.length<a;)b.push(Z(b[b.length-1]+this.tickInterval));this.transA*=(e-1)/(a-1);this.max=b[b.length-1]}u(d)&&a!==d&&(this.isDirty=!0)}},setScale:function(){var a=this.stacks,b,c,d,e;this.oldMin=this.min;this.oldMax=this.max;this.oldAxisLength=this.len;this.setAxisSize();e=this.len!==this.oldAxisLength;t(this.series,function(a){if(a.isDirtyData||a.isDirty||
a.xAxis.isDirty)d=!0});if(e||d||this.isLinked||this.forceRedraw||this.userMin!==this.oldUserMin||this.userMax!==this.oldUserMax){if(!this.isXAxis)for(b in a)for(c in a[b])a[b][c].total=null,a[b][c].cum=0;this.forceRedraw=!1;this.getSeriesExtremes();this.setTickPositions();this.oldUserMin=this.userMin;this.oldUserMax=this.userMax;this.isDirty||(this.isDirty=e||this.min!==this.oldMin||this.max!==this.oldMax)}else if(!this.isXAxis)for(b in this.oldStacks&&(a=this.stacks=this.oldStacks),a)for(c in a[b])a[b][c].cum=
a[b][c].total;this.setMaxTicks()},setExtremes:function(a,b,c,d,e){var f=this,g=f.chart;c=k(c,!0);e=s(e,{min:a,max:b});W(f,"setExtremes",e,function(){f.userMin=a;f.userMax=b;f.eventArgs=e;f.isDirtyExtremes=!0;c&&g.redraw(d)})},zoom:function(a,b){var c=this.dataMin,d=this.dataMax,e=this.options;this.allowZoomOutside||(u(c)&&a<=ga(c,k(e.min,c))&&(a=A),u(d)&&b>=z(d,k(e.max,d))&&(b=A));this.displayBtn=a!==A||b!==A;this.setExtremes(a,b,!1,A,{trigger:"zoom"});return!0},setAxisSize:function(){var a=this.chart,
b=this.options,c=b.offsetLeft||0,d=this.horiz,e=k(b.width,a.plotWidth-c+(b.offsetRight||0)),f=k(b.height,a.plotHeight),g=k(b.top,a.plotTop),b=k(b.left,a.plotLeft+c),c=/%$/;c.test(f)&&(f=parseInt(f,10)/100*a.plotHeight);c.test(g)&&(g=parseInt(g,10)/100*a.plotHeight+a.plotTop);this.left=b;this.top=g;this.width=e;this.height=f;this.bottom=a.chartHeight-f-g;this.right=a.chartWidth-e-b;this.len=z(d?e:f,0);this.pos=d?b:g},getExtremes:function(){var a=this.isLog;return{min:a?Z(O(this.min)):this.min,max:a?
Z(O(this.max)):this.max,dataMin:this.dataMin,dataMax:this.dataMax,userMin:this.userMin,userMax:this.userMax}},getThreshold:function(a){var b=this.isLog,c=b?O(this.min):this.min,b=b?O(this.max):this.max;c>a||null===a?a=c:b<a&&(a=b);return this.translate(a,0,1,0,1)},autoLabelAlign:function(a){a=(k(a,0)-90*this.side+720)%360;return 15<a&&165>a?"right":195<a&&345>a?"left":"center"},getOffset:function(){var a=this,b=a.chart,c=b.renderer,d=a.options,e=a.tickPositions,f=a.ticks,g=a.horiz,h=a.side,l=b.inverted?
[1,0,3,2][h]:h,m,q=0,p,v=0,n=d.title,H=d.labels,x=0,r=b.axisOffset,y=b.clipOffset,w=[-1,1,1,-1][h],s,L=1,F=k(H.maxStaggerLines,5),B,D,C,X,I=2===h?c.fontMetrics(H.style.fontSize).b:0;a.hasData=m=a.hasVisibleSeries||u(a.min)&&u(a.max)&&!!e;a.showAxis=b=m||k(d.showEmpty,!0);a.staggerLines=a.horiz&&H.staggerLines;a.axisGroup||(a.gridGroup=c.g("grid").attr({zIndex:d.gridZIndex||1}).add(),a.axisGroup=c.g("axis").attr({zIndex:d.zIndex||2}).add(),a.labelGroup=c.g("axis-labels").attr({zIndex:H.zIndex||7}).addClass("highcharts-"+
a.coll.toLowerCase()+"-labels").add());if(m||a.isLinked){a.labelAlign=k(H.align||a.autoLabelAlign(H.rotation));t(e,function(b){f[b]?f[b].addLabel():f[b]=new ba(a,b)});if(a.horiz&&!a.staggerLines&&F&&!H.rotation){for(s=a.reversed?[].concat(e).reverse():e;L<F;){m=[];B=!1;for(H=0;H<s.length;H++)D=s[H],C=(C=f[D].label&&f[D].label.getBBox())?C.width:0,X=H%L,C&&(D=a.translate(D),m[X]!==A&&D<m[X]&&(B=!0),m[X]=D+C);if(B)L++;else break}1<L&&(a.staggerLines=L)}t(e,function(b){if(0===h||2===h||{1:"left",3:"right"}[h]===
a.labelAlign)x=z(f[b].getLabelSize(),x)});a.staggerLines&&(x*=a.staggerLines,a.labelOffset=x)}else for(s in f)f[s].destroy(),delete f[s];n&&n.text&&!1!==n.enabled&&(a.axisTitle||(a.axisTitle=c.text(n.text,0,0,n.useHTML).attr({zIndex:7,rotation:n.rotation||0,align:n.textAlign||{low:"left",middle:"center",high:"right"}[n.align]}).addClass("highcharts-"+this.coll.toLowerCase()+"-title").css(n.style).add(a.axisGroup),a.axisTitle.isNew=!0),b&&(q=a.axisTitle.getBBox()[g?"height":"width"],v=k(n.margin,g?
5:10),p=n.offset),a.axisTitle[b?"show":"hide"]());a.offset=w*k(d.offset,r[h]);a.axisTitleMargin=k(p,x+v+(x&&w*d.labels[g?"y":"x"]-I));r[h]=z(r[h],a.axisTitleMargin+q+w*a.offset);y[l]=z(y[l],2*ca(d.lineWidth/2))},getLinePath:function(a){var b=this.chart,c=this.opposite,d=this.offset,e=this.horiz,f=this.left+(c?this.width:0)+d,d=b.chartHeight-this.bottom-(c?this.height:0)+d;c&&(a*=-1);return b.renderer.crispLine(["M",e?this.left:f,e?d:this.top,"L",e?b.chartWidth-this.right:f,e?d:b.chartHeight-this.bottom],
a)},getTitlePosition:function(){var a=this.horiz,b=this.left,c=this.top,d=this.len,e=this.options.title,f=a?b:c,g=this.opposite,h=this.offset,l=B(e.style.fontSize||12),d={low:f+(a?0:d),middle:f+d/2,high:f+(a?d:0)}[e.align],b=(a?c+this.height:b)+(a?1:-1)*(g?-1:1)*this.axisTitleMargin+(2===this.side?l:0);return{x:a?d:b+(g?this.width:0)+h+(e.x||0),y:a?b-(g?this.height:0)+h:d+(e.y||0)}},render:function(){var a=this,b=a.horiz,c=a.reversed,d=a.chart,e=d.renderer,f=a.options,g=a.isLog,h=a.isLinked,l=a.tickPositions,
m,q=a.axisTitle,p=a.ticks,v=a.minorTicks,n=a.alternateBands,k=f.stackLabels,x=f.alternateGridColor,r=a.tickmarkOffset,w=f.lineWidth,y=d.hasRendered&&u(a.oldMin)&&!isNaN(a.oldMin),s=a.hasData,L=a.showAxis,z,F=f.labels.overflow,D=a.justifyLabels=b&&!1!==F,C;a.labelEdge.length=0;a.justifyToPlot="justify"===F;t([p,v,n],function(a){for(var b in a)a[b].isActive=!1});if(s||h)a.minorTickInterval&&!a.categories&&t(a.getMinorTickPositions(),function(b){v[b]||(v[b]=new ba(a,b,"minor"));y&&v[b].isNew&&v[b].render(null,
!0);v[b].render(null,!1,1)}),l.length&&(m=l.slice(),(b&&c||!b&&!c)&&m.reverse(),D&&(m=m.slice(1).concat([m[0]])),t(m,function(b,c){D&&(c=c===m.length-1?0:c+1);if(!h||b>=a.min&&b<=a.max)p[b]||(p[b]=new ba(a,b)),y&&p[b].isNew&&p[b].render(c,!0,0.1),p[b].render(c,!1,1)}),r&&0===a.min&&(p[-1]||(p[-1]=new ba(a,-1,null,!0)),p[-1].render(-1))),x&&t(l,function(b,c){0===c%2&&b<a.max&&(n[b]||(n[b]=new sa.PlotLineOrBand(a)),z=b+r,C=l[c+1]!==A?l[c+1]+r:a.max,n[b].options={from:g?O(z):z,to:g?O(C):C,color:x},n[b].render(),
n[b].isActive=!0)}),a._addedPlotLB||(t((f.plotLines||[]).concat(f.plotBands||[]),function(b){a.addPlotBandOrLine(b)}),a._addedPlotLB=!0);t([p,v,n],function(a){var b,c,e=[],f=da?da.duration||500:0,g=function(){for(c=e.length;c--;)a[e[c]]&&!a[e[c]].isActive&&(a[e[c]].destroy(),delete a[e[c]])};for(b in a)a[b].isActive||(a[b].render(b,!1,0),a[b].isActive=!1,e.push(b));a!==n&&d.hasRendered&&f?f&&setTimeout(g,f):g()});w&&(b=a.getLinePath(w),a.axisLine?a.axisLine.animate({d:b}):a.axisLine=e.path(b).attr({stroke:f.lineColor,
"stroke-width":w,zIndex:7}).add(a.axisGroup),a.axisLine[L?"show":"hide"]());q&&L&&(q[q.isNew?"attr":"animate"](a.getTitlePosition()),q.isNew=!1);k&&k.enabled&&a.renderStackTotals();a.isDirty=!1},redraw:function(){var a=this.chart.pointer;a&&a.reset(!0);this.render();t(this.plotLinesAndBands,function(a){a.render()});t(this.series,function(a){a.isDirty=!0})},destroy:function(a){var b=this,c=b.stacks,d,e=b.plotLinesAndBands;a||ea(b);for(d in c)pa(c[d]),c[d]=null;t([b.ticks,b.minorTicks,b.alternateBands],
function(a){pa(a)});for(a=e.length;a--;)e[a].destroy();t("stackTotalGroup axisLine axisTitle axisGroup cross gridGroup labelGroup".split(" "),function(a){b[a]&&(b[a]=b[a].destroy())});this.cross&&this.cross.destroy()},drawCrosshair:function(a,b){if(this.crosshair)if(!1===(u(b)||!k(this.crosshair.snap,!0)))this.hideCrosshair();else{var c,d=this.crosshair,e=d.animation;k(d.snap,!0)?u(b)&&(c=this.chart.inverted!=this.horiz?b.plotX:this.len-b.plotY):c=this.horiz?a.chartX-this.pos:this.len-a.chartY+this.pos;
c=this.isRadial?this.getPlotLinePath(this.isXAxis?b.x:k(b.stackY,b.y)):this.getPlotLinePath(null,null,null,null,c);if(null===c)this.hideCrosshair();else if(this.cross)this.cross.attr({visibility:"visible"})[e?"animate":"attr"]({d:c},e);else e={"stroke-width":d.width||1,stroke:d.color||"#C0C0C0",zIndex:d.zIndex||2},d.dashStyle&&(e.dashstyle=d.dashStyle),this.cross=this.chart.renderer.path(c).attr(e).add()}},hideCrosshair:function(){this.cross&&this.cross.hide()}};s(Ca.prototype,void 0);var Oa=sa.Legend=
function(a,b){this.init(a,b)};Oa.prototype={init:function(a,b){var c=this,d=b.itemStyle,e=k(b.padding,8),f=b.itemMarginTop||0;this.options=b;b.enabled&&(c.baseline=B(d.fontSize)+3+f,c.itemStyle=d,c.itemHiddenStyle=E(d,b.itemHiddenStyle),c.itemMarginTop=f,c.padding=e,c.initialItemX=e,c.initialItemY=e-5,c.maxItemWidth=0,c.chart=a,c.itemHeight=0,c.lastLineHeight=0,c.symbolWidth=k(b.symbolWidth,16),c.pages=[],c.render(),V(c.chart,"endResize",function(){c.positionCheckboxes()}))},colorizeItem:function(a,
b){var c=this.options,d=a.legendItem,e=a.legendLine,f=a.legendSymbol,g=this.itemHiddenStyle.color,c=b?c.itemStyle.color:g,h=b?a.legendColor||a.color||"#CCC":g,g=a.options&&a.options.marker,l={fill:h},m;d&&d.css({fill:c,color:c});e&&e.attr({stroke:h});if(f){if(g&&f.isMarker)for(m in l.stroke=h,g=a.convertAttribs(g),g)d=g[m],d!==A&&(l[m]=d);f.attr(l)}},positionItem:function(a){var b=this.options,c=b.symbolPadding,b=!b.rtl,d=a._legendItemPos,e=d[0],d=d[1],f=a.checkbox;a.legendGroup&&a.legendGroup.translate(b?
e:this.legendWidth-e-2*c-4,d);f&&(f.x=e,f.y=d)},destroyItem:function(a){var b=a.checkbox;t(["legendItem","legendLine","legendSymbol","legendGroup"],function(b){a[b]&&(a[b]=a[b].destroy())});b&&qa(a.checkbox)},destroy:function(){var a=this.group,b=this.box;b&&(this.box=b.destroy());a&&(this.group=a.destroy())},positionCheckboxes:function(a){var b=this.group.alignAttr,c,d=this.clipHeight||this.legendHeight;b&&(c=b.translateY,t(this.allItems,function(e){var f=e.checkbox,g;f&&(g=c+f.y+(a||0)+3,K(f,{left:b.translateX+
e.legendItemWidth+f.x-20+"px",top:g+"px",display:g>c-6&&g<c+d-6?"":aa}))}))},renderTitle:function(){var a=this.padding,b=this.options.title,c=0;b.text&&(this.title||(this.title=this.chart.renderer.label(b.text,a-3,a-4,null,null,null,null,null,"legend-title").attr({zIndex:1}).css(b.style).add(this.group)),a=this.title.getBBox(),c=a.height,this.offsetWidth=a.width,this.contentGroup.attr({translateY:c}));this.titleHeight=c},renderItem:function(a){var b=this.chart,c=b.renderer,d=this.options,e="horizontal"===
d.layout,f=this.symbolWidth,g=d.symbolPadding,h=this.itemStyle,l=this.itemHiddenStyle,m=this.padding,q=e?k(d.itemDistance,20):0,p=!d.rtl,v=d.width,n=d.itemMarginBottom||0,x=this.itemMarginTop,r=this.initialItemX,t=a.legendItem,w=a.series&&a.series.drawLegendSymbol?a.series:a,s=w.options,s=this.createCheckboxForItem&&s&&s.showCheckbox,u=d.useHTML;t||(a.legendGroup=c.g("legend-item").attr({zIndex:1}).add(this.scrollGroup),w.drawLegendSymbol(this,a),a.legendItem=t=c.text(d.labelFormat?y(d.labelFormat,
a):d.labelFormatter.call(a),p?f+g:-g,this.baseline,u).css(E(a.visible?h:l)).attr({align:p?"left":"right",zIndex:2}).add(a.legendGroup),this.setItemEvents&&this.setItemEvents(a,t,u,h,l),this.colorizeItem(a,a.visible),s&&this.createCheckboxForItem(a));c=t.getBBox();f=a.legendItemWidth=d.itemWidth||a.legendItemWidth||f+g+c.width+q+(s?20:0);this.itemHeight=g=C(a.legendItemHeight||c.height);e&&this.itemX-r+f>(v||b.chartWidth-2*m-r-d.x)&&(this.itemX=r,this.itemY+=x+this.lastLineHeight+n,this.lastLineHeight=
0);this.maxItemWidth=z(this.maxItemWidth,f);this.lastItemY=x+this.itemY+n;this.lastLineHeight=z(g,this.lastLineHeight);a._legendItemPos=[this.itemX,this.itemY];e?this.itemX+=f:(this.itemY+=x+g+n,this.lastLineHeight=g);this.offsetWidth=v||z((e?this.itemX-r-q:f)+m,this.offsetWidth)},getAllItems:function(){var a=[];t(this.chart.series,function(b){var c=b.options;k(c.showInLegend,u(c.linkedTo)?!1:A,!0)&&(a=a.concat(b.legendItems||("point"===c.legendType?b.data:b)))});return a},render:function(){var a=
this,b=a.chart,c=b.renderer,d=a.group,e,f,g,h,l=a.box,m=a.options,q=a.padding,p=m.borderWidth,v=m.backgroundColor;a.itemX=a.initialItemX;a.itemY=a.initialItemY;a.offsetWidth=0;a.lastItemY=0;d||(a.group=d=c.g("legend").attr({zIndex:7}).add(),a.contentGroup=c.g().attr({zIndex:1}).add(d),a.scrollGroup=c.g().add(a.contentGroup));a.renderTitle();e=a.getAllItems();D(e,function(a,b){return(a.options&&a.options.legendIndex||0)-(b.options&&b.options.legendIndex||0)});m.reversed&&e.reverse();a.allItems=e;a.display=
f=!!e.length;t(e,function(b){a.renderItem(b)});g=m.width||a.offsetWidth;h=a.lastItemY+a.lastLineHeight+a.titleHeight;h=a.handleOverflow(h);if(p||v)g+=q,h+=q,l?0<g&&0<h&&(l[l.isNew?"attr":"animate"](l.crisp({width:g,height:h})),l.isNew=!1):(a.box=l=c.rect(0,0,g,h,m.borderRadius,p||0).attr({stroke:m.borderColor,"stroke-width":p||0,fill:v||aa}).add(d).shadow(m.shadow),l.isNew=!0),l[f?"show":"hide"]();a.legendWidth=g;a.legendHeight=h;t(e,function(b){a.positionItem(b)});f&&d.align(s({width:g,height:h},
m),!0,"spacingBox");b.isResizing||this.positionCheckboxes()},handleOverflow:function(a){var b=this,c=this.chart,d=c.renderer,e=this.options,f=e.y,f=c.spacingBox.height+("top"===e.verticalAlign?-f:f)-this.padding,g=e.maxHeight,h,l=this.clipRect,m=e.navigation,q=k(m.animation,!0),p=m.arrowSize||12,v=this.nav,n=this.pages,x,r=this.allItems;"horizontal"===e.layout&&(f/=2);g&&(f=ga(f,g));n.length=0;a>f&&!e.useHTML?(this.clipHeight=h=f-20-this.titleHeight-this.padding,this.currentPage=k(this.currentPage,
1),this.fullHeight=a,t(r,function(a,b){var c=a._legendItemPos[1],d=C(a.legendItem.getBBox().height),e=n.length;if(!e||c-n[e-1]>h&&(x||c)!==n[e-1])n.push(x||c),e++;b===r.length-1&&c+d-n[e-1]>h&&n.push(c);c!==x&&(x=c)}),l||(l=b.clipRect=d.clipRect(0,this.padding,9999,0),b.contentGroup.clip(l)),l.attr({height:h}),v||(this.nav=v=d.g().attr({zIndex:1}).add(this.group),this.up=d.symbol("triangle",0,0,p,p).on("click",function(){b.scroll(-1,q)}).add(v),this.pager=d.text("",15,10).css(m.style).add(v),this.down=
d.symbol("triangle-down",0,0,p,p).on("click",function(){b.scroll(1,q)}).add(v)),b.scroll(0),a=f):v&&(l.attr({height:c.chartHeight}),v.hide(),this.scrollGroup.attr({translateY:1}),this.clipHeight=0);return a},scroll:function(a,b){var c=this.pages,d=c.length,e=this.currentPage+a,f=this.clipHeight,g=this.options.navigation,h=g.activeColor,g=g.inactiveColor,l=this.pager,m=this.padding;e>d&&(e=d);0<e&&(b!==A&&(da=k(b,this.chart.animation)),this.nav.attr({translateX:m,translateY:f+this.padding+7+this.titleHeight,
visibility:"visible"}),this.up.attr({fill:1===e?g:h}).css({cursor:1===e?"default":"pointer"}),l.attr({text:e+"/"+d}),this.down.attr({x:18+this.pager.getBBox().width,fill:e===d?g:h}).css({cursor:e===d?"default":"pointer"}),c=-c[e-1]+this.initialItemY,this.scrollGroup.animate({translateY:c}),this.currentPage=e,this.positionCheckboxes(c))}};var qb=sa.LegendSymbolMixin={drawRectangle:function(a,b){var c=a.options.symbolHeight||12;b.legendSymbol=this.chart.renderer.rect(0,a.baseline-5-c/2,a.symbolWidth,
c,a.options.symbolRadius||0).attr({zIndex:3}).add(b.legendGroup)},drawLineMarker:function(a){var b=this.options,c=b.marker,d;d=a.symbolWidth;var e=this.chart.renderer,f=this.legendGroup;a=a.baseline-C(0.3*e.fontMetrics(a.options.itemStyle.fontSize).b);var g;b.lineWidth&&(g={"stroke-width":b.lineWidth},b.dashStyle&&(g.dashstyle=b.dashStyle),this.legendLine=e.path(["M",0,a,"L",d,a]).attr(g).add(f));c&&!1!==c.enabled&&(b=c.radius,this.legendSymbol=d=e.symbol(this.symbol,d/2-b,a-b,2*b,2*b).add(f),d.isMarker=
!0)}};(/Trident\/7\.0/.test(ra)||Ea)&&L(Oa.prototype,"positionItem",function(a,b){var c=this,d=function(){b._legendItemPos&&a.call(c,b)};d();setTimeout(d)});Ia.prototype={init:function(a,b){var c,d=a.series;a.series=null;c=E(Q,a);c.series=a.series=d;this.userOptions=a;d=c.chart;this.margin=this.splashArray("margin",d);this.spacing=this.splashArray("spacing",d);var e=d.events;this.bounds={h:{},v:{}};this.callback=b;this.isResizing=0;this.options=c;this.axes=[];this.series=[];this.hasCartesianSeries=
d.showAxes;var f=this,g;f.index=ma.length;ma.push(f);cb++;!1!==d.reflow&&V(f,"load",function(){f.initReflow()});if(e)for(g in e)V(f,g,e[g]);f.xAxis=[];f.yAxis=[];f.animation=ja?!1:k(d.animation,!0);f.pointCount=0;f.counters=new Aa;f.firstRender()},initSeries:function(a){var b=this.options.chart;(b=wa[a.type||b.type||b.defaultSeriesType])||I(17,!0);b=new b;b.init(this,a);return b},isInsidePlot:function(a,b,c){var d=c?b:a;a=c?a:b;return 0<=d&&d<=this.plotWidth&&0<=a&&a<=this.plotHeight},adjustTickAmounts:function(){!1!==
this.options.chart.alignTicks&&t(this.axes,function(a){a.adjustTickAmount()});this.maxTicks=null},redraw:function(a){var b=this.axes,c=this.series,d=this.pointer,e=this.legend,f=this.isDirtyLegend,g,h,l=this.isDirtyBox,m=c.length,q=m,p=this.renderer,v=p.isHidden(),n=[];da=k(a,this.animation);v&&this.cloneRenderTo();for(this.layOutTitles();q--;)if(a=c[q],a.options.stacking&&(g=!0,a.isDirty)){h=!0;break}if(h)for(q=m;q--;)a=c[q],a.options.stacking&&(a.isDirty=!0);t(c,function(a){a.isDirty&&"point"===
a.options.legendType&&(f=!0)});f&&e.options.enabled&&(e.render(),this.isDirtyLegend=!1);g&&this.getStacks();this.hasCartesianSeries&&(this.isResizing||(this.maxTicks=null,t(b,function(a){a.setScale()})),this.adjustTickAmounts(),this.getMargins(),t(b,function(a){a.isDirty&&(l=!0)}),t(b,function(a){a.isDirtyExtremes&&(a.isDirtyExtremes=!1,n.push(function(){W(a,"afterSetExtremes",s(a.eventArgs,a.getExtremes()));delete a.eventArgs}));(l||g)&&a.redraw()}));l&&this.drawChartBox();t(c,function(a){a.isDirty&&
a.visible&&(!a.isCartesian||a.xAxis)&&a.redraw()});d&&d.reset(!0);p.draw();W(this,"redraw");v&&this.cloneRenderTo(!0);t(n,function(a){a.call()})},get:function(a){var b=this.axes,c=this.series,d,e;for(d=0;d<b.length;d++)if(b[d].options.id===a)return b[d];for(d=0;d<c.length;d++)if(c[d].options.id===a)return c[d];for(d=0;d<c.length;d++)for(e=c[d].points||[],b=0;b<e.length;b++)if(e[b].id===a)return e[b];return null},getAxes:function(){var a=this,b=this.options,c=b.xAxis=ka(b.xAxis||{}),b=b.yAxis=ka(b.yAxis||
{});t(c,function(a,b){a.index=b;a.isX=!0});t(b,function(a,b){a.index=b});c=c.concat(b);t(c,function(b){new Ca(a,b)});a.adjustTickAmounts()},getSelectedPoints:function(){var a=[];t(this.series,function(b){a=a.concat(db(b.points||[],function(a){return a.selected}))});return a},getSelectedSeries:function(){return db(this.series,function(a){return a.selected})},getStacks:function(){var a=this;t(a.yAxis,function(a){a.stacks&&a.hasVisibleSeries&&(a.oldStacks=a.stacks)});t(a.series,function(b){!b.options.stacking||
!0!==b.visible&&!1!==a.options.chart.ignoreHiddenSeries||(b.stackKey=b.type+k(b.options.stack,""))})},setTitle:function(a,b,c){var d=this,e=d.options,f;f=e.title=E(e.title,a);e=e.subtitle=E(e.subtitle,b);t([["title",a,f],["subtitle",b,e]],function(a){var b=a[0],c=d[b],e=a[1];a=a[2];c&&e&&(d[b]=c=c.destroy());a&&a.text&&!c&&(d[b]=d.renderer.text(a.text,0,0,a.useHTML).attr({align:a.align,"class":"highcharts-"+b,zIndex:a.zIndex||4}).css(a.style).add())});d.layOutTitles(c)},layOutTitles:function(a){var b=
0,c=this.title,d=this.subtitle,e=this.options,f=e.title,e=e.subtitle,g=this.spacingBox.width-44;c&&(c.css({width:(f.width||g)+"px"}).align(s({y:15},f),!1,"spacingBox"),f.floating||f.verticalAlign||(b=c.getBBox().height));d&&(d.css({width:(e.width||g)+"px"}).align(s({y:b+f.margin},e),!1,"spacingBox"),e.floating||e.verticalAlign||(b=ta(b+d.getBBox().height)));c=this.titleOffset!==b;this.titleOffset=b;!this.isDirtyBox&&c&&(this.isDirtyBox=c,this.hasRendered&&k(a,!0)&&this.isDirtyBox&&this.redraw())},
getChartSize:function(){var a=this.options.chart,b=a.width,a=a.height,c=this.renderToClone||this.renderTo;u(b)||(this.containerWidth=Ga(c,"width"));u(a)||(this.containerHeight=Ga(c,"height"));this.chartWidth=z(0,b||this.containerWidth||600);this.chartHeight=z(0,k(a,19<this.containerHeight?this.containerHeight:400))},cloneRenderTo:function(a){var b=this.renderToClone,c=this.container;a?b&&(this.renderTo.appendChild(c),qa(b),delete this.renderToClone):(c&&c.parentNode===this.renderTo&&this.renderTo.removeChild(c),
this.renderToClone=b=this.renderTo.cloneNode(0),K(b,{position:"absolute",top:"-9999px",display:"block"}),b.style.setProperty&&b.style.setProperty("display","block","important"),F.body.appendChild(b),c&&b.appendChild(c))},getContainer:function(){var a,b=this.options.chart,c,d,e;this.renderTo=a=b.renderTo;e="highcharts-"+Ja++;fa(a)&&(this.renderTo=a=F.getElementById(a));a||I(13,!0);c=B(G(a,"data-highcharts-chart"));!isNaN(c)&&ma[c]&&ma[c].hasRendered&&ma[c].destroy();G(a,"data-highcharts-chart",this.index);
a.innerHTML="";b.skipClone||a.offsetWidth||this.cloneRenderTo();this.getChartSize();c=this.chartWidth;d=this.chartHeight;this.container=a=ia(Qa,{className:"highcharts-container"+(b.className?" "+b.className:""),id:e},s({position:"relative",overflow:"hidden",width:c+"px",height:d+"px",textAlign:"left",lineHeight:"normal",zIndex:0,"-webkit-tap-highlight-color":"rgba(0,0,0,0)"},b.style),this.renderToClone||a);this._cursor=a.style.cursor;this.renderer=b.forExport?new ya(a,c,d,b.style,!0):new ya(a,c,d,
b.style);ja&&this.renderer.create(this,a,c,d)},getMargins:function(){var a=this.spacing,b,c=this.legend,d=this.margin,e=this.options.legend,f=k(e.margin,20),g=e.x,h=e.y,l=e.align,m=e.verticalAlign,q=this.titleOffset;this.resetMargins();b=this.axisOffset;q&&!u(d[0])&&(this.plotTop=z(this.plotTop,q+this.options.title.margin+a[0]));c.display&&!e.floating&&("right"===l?u(d[1])||(this.marginRight=z(this.marginRight,c.legendWidth-g+f+a[1])):"left"===l?u(d[3])||(this.plotLeft=z(this.plotLeft,c.legendWidth+
g+f+a[3])):"top"===m?u(d[0])||(this.plotTop=z(this.plotTop,c.legendHeight+h+f+a[0])):"bottom"!==m||u(d[2])||(this.marginBottom=z(this.marginBottom,c.legendHeight-h+f+a[2])));this.extraBottomMargin&&(this.marginBottom+=this.extraBottomMargin);this.extraTopMargin&&(this.plotTop+=this.extraTopMargin);this.hasCartesianSeries&&t(this.axes,function(a){a.getOffset()});u(d[3])||(this.plotLeft+=b[3]);u(d[0])||(this.plotTop+=b[0]);u(d[2])||(this.marginBottom+=b[2]);u(d[1])||(this.marginRight+=b[1]);this.setChartSize()},
reflow:function(a){var b=this,c=b.options.chart,d=b.renderTo,e=c.width||Ga(d,"width"),f=c.height||Ga(d,"height"),c=a?a.target:M,d=function(){b.container&&(b.setSize(e,f,!1),b.hasUserSize=null)};if(!b.hasUserSize&&e&&f&&(c===M||c===F)){if(e!==b.containerWidth||f!==b.containerHeight)clearTimeout(b.reflowTimeout),a?b.reflowTimeout=setTimeout(d,100):d();b.containerWidth=e;b.containerHeight=f}},initReflow:function(){var a=this,b=function(b){a.reflow(b)};V(M,"resize",b);V(a,"destroy",function(){ea(M,"resize",
b)})},setSize:function(a,b,c){var d=this,e,f,g;d.isResizing+=1;g=function(){d&&W(d,"endResize",null,function(){d.isResizing-=1})};da=k(c,d.animation);d.oldChartHeight=d.chartHeight;d.oldChartWidth=d.chartWidth;u(a)&&(d.chartWidth=e=z(0,C(a)),d.hasUserSize=!!e);u(b)&&(d.chartHeight=f=z(0,C(b)));(da?fb:K)(d.container,{width:e+"px",height:f+"px"},da);d.setChartSize(!0);d.renderer.setSize(e,f,c);d.maxTicks=null;t(d.axes,function(a){a.isDirty=!0;a.setScale()});t(d.series,function(a){a.isDirty=!0});d.isDirtyLegend=
!0;d.isDirtyBox=!0;d.layOutTitles();d.getMargins();d.redraw(c);d.oldChartHeight=null;W(d,"resize");!1===da?g():setTimeout(g,da&&da.duration||500)},setChartSize:function(a){var b=this.inverted,c=this.renderer,d=this.chartWidth,e=this.chartHeight,f=this.options.chart,g=this.spacing,h=this.clipOffset,l,m,q,p;this.plotLeft=l=C(this.plotLeft);this.plotTop=m=C(this.plotTop);this.plotWidth=q=z(0,C(d-l-this.marginRight));this.plotHeight=p=z(0,C(e-m-this.marginBottom));this.plotSizeX=b?p:q;this.plotSizeY=
b?q:p;this.plotBorderWidth=f.plotBorderWidth||0;this.spacingBox=c.spacingBox={x:g[3],y:g[0],width:d-g[3]-g[1],height:e-g[0]-g[2]};this.plotBox=c.plotBox={x:l,y:m,width:q,height:p};d=2*ca(this.plotBorderWidth/2);b=ta(z(d,h[3])/2);c=ta(z(d,h[0])/2);this.clipBox={x:b,y:c,width:ca(this.plotSizeX-z(d,h[1])/2-b),height:ca(this.plotSizeY-z(d,h[2])/2-c)};a||t(this.axes,function(a){a.setAxisSize();a.setAxisTranslation()})},resetMargins:function(){var a=this.spacing,b=this.margin;this.plotTop=k(b[0],a[0]);
this.marginRight=k(b[1],a[1]);this.marginBottom=k(b[2],a[2]);this.plotLeft=k(b[3],a[3]);this.axisOffset=[0,0,0,0];this.clipOffset=[0,0,0,0]},drawChartBox:function(){var a=this.options.chart,b=this.renderer,c=this.chartWidth,d=this.chartHeight,e=this.chartBackground,f=this.plotBackground,g=this.plotBorder,h=this.plotBGImage,l=a.borderWidth||0,m=a.backgroundColor,q=a.plotBackgroundColor,p=a.plotBackgroundImage,k=a.plotBorderWidth||0,n,x=this.plotLeft,r=this.plotTop,t=this.plotWidth,w=this.plotHeight,
s=this.plotBox,y=this.clipRect,u=this.clipBox;n=l+(a.shadow?8:0);if(l||m)e?e.animate(e.crisp({width:c-n,height:d-n})):(e={fill:m||aa},l&&(e.stroke=a.borderColor,e["stroke-width"]=l),this.chartBackground=b.rect(n/2,n/2,c-n,d-n,a.borderRadius,l).attr(e).addClass("highcharts-background").add().shadow(a.shadow));q&&(f?f.animate(s):this.plotBackground=b.rect(x,r,t,w,0).attr({fill:q}).add().shadow(a.plotShadow));p&&(h?h.animate(s):this.plotBGImage=b.image(p,x,r,t,w).add());y?y.animate({width:u.width,height:u.height}):
this.clipRect=b.clipRect(u);k&&(g?g.animate(g.crisp({x:x,y:r,width:t,height:w})):this.plotBorder=b.rect(x,r,t,w,0,-k).attr({stroke:a.plotBorderColor,"stroke-width":k,fill:aa,zIndex:1}).add());this.isDirtyBox=!1},propFromSeries:function(){var a=this,b=a.options.chart,c,d=a.options.series,e,f;t(["inverted","angular","polar"],function(g){c=wa[b.type||b.defaultSeriesType];f=a[g]||b[g]||c&&c.prototype[g];for(e=d&&d.length;!f&&e--;)(c=wa[d[e].type])&&c.prototype[g]&&(f=!0);a[g]=f})},linkSeries:function(){var a=
this,b=a.series;t(b,function(a){a.linkedSeries.length=0});t(b,function(b){var d=b.options.linkedTo;fa(d)&&(d=":previous"===d?a.series[b.index-1]:a.get(d))&&(d.linkedSeries.push(b),b.linkedParent=d)})},renderSeries:function(){t(this.series,function(a){a.translate();a.setTooltipPoints&&a.setTooltipPoints();a.render()})},render:function(){var a=this,b=a.axes,c=a.renderer,d=a.options,e=d.labels,f=d.credits,g;a.setTitle();a.legend=new Oa(a,d.legend);a.getStacks();t(b,function(a){a.setScale()});a.getMargins();
a.maxTicks=null;t(b,function(a){a.setTickPositions(!0);a.setMaxTicks()});a.adjustTickAmounts();a.getMargins();a.drawChartBox();a.hasCartesianSeries&&t(b,function(a){a.render()});a.seriesGroup||(a.seriesGroup=c.g("series-group").attr({zIndex:3}).add());a.renderSeries();e.items&&t(e.items,function(b){var d=s(e.style,b.style),f=B(d.left)+a.plotLeft,g=B(d.top)+a.plotTop+12;delete d.left;delete d.top;c.text(b.html,f,g).attr({zIndex:2}).css(d).add()});f.enabled&&!a.credits&&(g=f.href,a.credits=c.text(f.text,
0,0).on("click",function(){g&&(location.href=g)}).attr({align:f.position.align,zIndex:8}).css(f.style).add().align(f.position));a.hasRendered=!0},destroy:function(){var a=this,b=a.axes,c=a.series,d=a.container,e,f=d&&d.parentNode;W(a,"destroy");ma[a.index]=A;cb--;a.renderTo.removeAttribute("data-highcharts-chart");ea(a);for(e=b.length;e--;)b[e]=b[e].destroy();for(e=c.length;e--;)c[e]=c[e].destroy();t("title subtitle chartBackground plotBackground plotBGImage plotBorder seriesGroup clipRect credits pointer scroller rangeSelector legend resetZoomButton tooltip renderer".split(" "),
function(b){var c=a[b];c&&c.destroy&&(a[b]=c.destroy())});d&&(d.innerHTML="",ea(d),f&&qa(d));for(e in a)delete a[e]},isReadyToRender:function(){var a=this;return!$&&M==M.top&&"complete"!==F.readyState||ja&&!M.canvg?(ja?CanVGController.push(function(){a.firstRender()},a.options.global.canvasToolsURL):F.attachEvent("onreadystatechange",function(){F.detachEvent("onreadystatechange",a.firstRender);"complete"===F.readyState&&a.firstRender()}),!1):!0},firstRender:function(){var a=this,b=a.options,c=a.callback;
a.isReadyToRender()&&(a.getContainer(),W(a,"init"),a.resetMargins(),a.setChartSize(),a.propFromSeries(),a.getAxes(),t(b.series||[],function(b){a.initSeries(b)}),a.linkSeries(),W(a,"beforeRender"),sa.Pointer&&(a.pointer=new Pointer(a,b)),a.render(),a.renderer.draw(),c&&c.apply(a,[a]),t(a.callbacks,function(b){b.apply(a,[a])}),a.cloneRenderTo(!0),W(a,"load"))},splashArray:function(a,b){var c=b[a],c=J(c)?c:[c,c,c,c];return[k(b[a+"Top"],c[0]),k(b[a+"Right"],c[1]),k(b[a+"Bottom"],c[2]),k(b[a+"Left"],c[3])]}};
Ia.prototype.callbacks=[];var Ha=function(){};Ha.prototype={init:function(a,b,c){this.series=a;this.applyOptions(b,c);this.pointAttr={};a.options.colorByPoint&&(b=a.options.colors||a.chart.options.colors,this.color=this.color||b[a.colorCounter++],a.colorCounter===b.length&&(a.colorCounter=0));a.chart.pointCount++;return this},applyOptions:function(a,b){var c=this.series,d=c.pointValKey;a=Ha.prototype.optionsToObject.call(this,a);s(this,a);this.options=this.options?s(this.options,a):a;d&&(this.y=this[d]);
this.x===A&&c&&(this.x=b===A?c.autoIncrement():b);return this},optionsToObject:function(a){var b={},c=this.series,d=c.pointArrayMap||["y"],e=d.length,f=0,g=0;if("number"===typeof a||null===a)b[d[0]]=a;else if(Y(a))for(a.length>e&&(c=typeof a[0],"string"===c?b.name=a[0]:"number"===c&&(b.x=a[0]),f++);g<e;)b[d[g++]]=a[f++];else"object"===typeof a&&(b=a,a.dataLabels&&(c._hasPointLabels=!0),a.marker&&(c._hasPointMarkers=!0));return b},destroy:function(){var a=this.series.chart,b=a.hoverPoints,c;a.pointCount--;
b&&(this.setState(),T(b,this),b.length||(a.hoverPoints=null));if(this===a.hoverPoint)this.onMouseOut();if(this.graphic||this.dataLabel)ea(this),this.destroyElements();this.legendItem&&a.legend.destroyItem(this);for(c in this)this[c]=null},destroyElements:function(){for(var a="graphic dataLabel dataLabelUpper group connector shadowGroup".split(" "),b,c=6;c--;)b=a[c],this[b]&&(this[b]=this[b].destroy())},getLabelConfig:function(){return{x:this.category,y:this.y,key:this.name||this.category,series:this.series,
point:this,percentage:this.percentage,total:this.total||this.stackTotal}},tooltipFormatter:function(a){var b=this.series,c=b.tooltipOptions,d=k(c.valueDecimals,""),e=c.valuePrefix||"",f=c.valueSuffix||"";t(b.pointArrayMap||["y"],function(b){b="{point."+b;if(e||f)a=a.replace(b+"}",e+b+"}"+f);a=a.replace(b+"}",b+":,."+d+"f}")});return y(a,{point:this,series:this.series})},firePointEvent:function(a,b,c){var d=this,e=this.series.options;(e.point.events[a]||d.options&&d.options.events&&d.options.events[a])&&
this.importEvents();"click"===a&&e.allowPointSelect&&(c=function(a){d.select(null,a.ctrlKey||a.metaKey||a.shiftKey)});W(this,a,b,c)}};var Pa=function(){};Pa.prototype={isCartesian:!0,type:"line",pointClass:Ha,sorted:!0,requireSorting:!0,pointAttrToOptions:{stroke:"lineColor","stroke-width":"lineWidth",fill:"fillColor",r:"radius"},axisTypes:["xAxis","yAxis"],colorCounter:0,parallelArrays:["x","y"],init:function(a,b){var c=this,d,e,f=a.series,g=function(a,b){return k(a.options.index,a._i)-k(b.options.index,
b._i)};c.chart=a;c.options=b=c.setOptions(b);c.linkedSeries=[];c.bindAxes();s(c,{name:b.name,state:"",pointAttr:{},visible:!1!==b.visible,selected:!0===b.selected});ja&&(b.animation=!1);e=b.events;for(d in e)V(c,d,e[d]);if(e&&e.click||b.point&&b.point.events&&b.point.events.click||b.allowPointSelect)a.runTrackerClick=!0;c.getColor();c.getSymbol();t(c.parallelArrays,function(a){c[a+"Data"]=[]});c.setData(b.data,!1);c.isCartesian&&(a.hasCartesianSeries=!0);f.push(c);c._i=f.length-1;D(f,g);this.yAxis&&
D(this.yAxis.series,g);t(f,function(a,b){a.index=b;a.name=a.name||"Series "+(b+1)})},bindAxes:function(){var a=this,b=a.options,c=a.chart,d;t(a.axisTypes||[],function(e){t(c[e],function(c){d=c.options;if(b[e]===d.index||b[e]!==A&&b[e]===d.id||b[e]===A&&0===d.index)c.series.push(a),a[e]=c,c.isDirty=!0});a[e]||a.optionalAxis===e||I(18,!0)})},updateParallelArrays:function(a,b){var c=a.series,d=arguments;t(c.parallelArrays,"number"===typeof b?function(d){var f="y"===d&&c.toYData?c.toYData(a):a[d];c[d+
"Data"][b]=f}:function(a){Array.prototype[b].apply(c[a+"Data"],Array.prototype.slice.call(d,2))})},autoIncrement:function(){var a=this.options,b=this.xIncrement,b=k(b,a.pointStart,0);this.pointInterval=k(this.pointInterval,a.pointInterval,1);this.xIncrement=b+this.pointInterval;return b},getSegments:function(){var a=-1,b=[],c,d=this.points,e=d.length;if(e)if(this.options.connectNulls){for(c=e;c--;)null===d[c].y&&d.splice(c,1);d.length&&(b=[d])}else t(d,function(c,g){null===c.y?(g>a+1&&b.push(d.slice(a+
1,g)),a=g):g===e-1&&b.push(d.slice(a+1,g+1))});this.segments=b},setOptions:function(a){var b=this.chart,c=b.options.plotOptions,b=b.userOptions||{},d=b.plotOptions||{},e=c[this.type];this.userOptions=a;c=E(e,c.series,a);this.tooltipOptions=E(Q.tooltip,Q.plotOptions[this.type].tooltip,b.tooltip,d.series&&d.series.tooltip,d[this.type]&&d[this.type].tooltip,a.tooltip);null===e.marker&&delete c.marker;return c},getColor:function(){var a=this.options,b=this.userOptions,c=this.chart.options.colors,d=this.chart.counters,
e;e=a.color||Na[this.type].color;e||a.colorByPoint||(u(b._colorIndex)?a=b._colorIndex:(b._colorIndex=d.color,a=d.color++),e=c[a]);this.color=e;d.wrapColor(c.length)},getSymbol:function(){var a=this.userOptions,b=this.options.marker,c=this.chart,d=c.options.symbols,c=c.counters;this.symbol=b.symbol;this.symbol||(u(a._symbolIndex)?a=a._symbolIndex:(a._symbolIndex=c.symbol,a=c.symbol++),this.symbol=d[a]);/^url/.test(this.symbol)&&(b.radius=0);c.wrapSymbol(d.length)},drawLegendSymbol:qb.drawLineMarker,
setData:function(a,b,c,d){var e=this,f=e.points,g=f&&f.length||0,h,l=e.options,m=e.chart,q=null,p=e.xAxis,v=p&&!!p.categories,n=e.tooltipPoints,x=l.turboThreshold,r=this.xData,w=this.yData,s=(h=e.pointArrayMap)&&h.length;a=a||[];h=a.length;b=k(b,!0);if(!1===d||!h||g!==h||e.cropped||e.hasGroupedData){e.xIncrement=null;e.pointRange=v?1:l.pointRange;e.colorCounter=0;t(this.parallelArrays,function(a){e[a+"Data"].length=0});if(x&&h>x){for(c=0;null===q&&c<h;)q=a[c],c++;if(U(q)){v=k(l.pointStart,0);l=k(l.pointInterval,
1);for(c=0;c<h;c++)r[c]=v,w[c]=a[c],v+=l;e.xIncrement=v}else if(Y(q))if(s)for(c=0;c<h;c++)l=a[c],r[c]=l[0],w[c]=l.slice(1,s+1);else for(c=0;c<h;c++)l=a[c],r[c]=l[0],w[c]=l[1];else I(12)}else for(c=0;c<h;c++)a[c]!==A&&(l={series:e},e.pointClass.prototype.applyOptions.apply(l,[a[c]]),e.updateParallelArrays(l,c),v&&l.name&&(p.names[l.x]=l.name));fa(w[0])&&I(14,!0);e.data=[];e.options.data=a;for(c=g;c--;)f[c]&&f[c].destroy&&f[c].destroy();n&&(n.length=0);p&&(p.minRange=p.userMinRange);e.isDirty=e.isDirtyData=
m.isDirtyBox=!0;c=!1}else t(a,function(a,b){f[b].update(a,!1)});b&&m.redraw(c)},processData:function(a){var b=this.xData,c=this.yData,d=b.length,e;e=0;var f,g,h=this.xAxis,l=this.options,m=l.cropThreshold,q=0,p=this.isCartesian,k,n;if(p&&!(this.isDirty||h.isDirty||this.yAxis.isDirty||a))return!1;if(p&&this.sorted&&(!m||d>m||this.forceCrop))if(k=h.min,n=h.max,b[d-1]<k||b[0]>n)b=[],c=[];else if(b[0]<k||b[d-1]>n)e=this.cropData(this.xData,this.yData,k,n),b=e.xData,c=e.yData,e=e.start,f=!0,q=b.length;
for(d=b.length-1;0<=d;d--)a=b[d]-b[d-1],!f&&b[d]>k&&b[d]<n&&q++,0<a&&(g===A||a<g)?g=a:0>a&&this.requireSorting&&I(15);this.cropped=f;this.cropStart=e;this.processedXData=b;this.processedYData=c;this.activePointCount=q;null===l.pointRange&&(this.pointRange=g||1);this.closestPointRange=g},cropData:function(a,b,c,d){var e=a.length,f=0,g=e,h=k(this.cropShoulder,1),l;for(l=0;l<e;l++)if(a[l]>=c){f=z(0,l-h);break}for(;l<e;l++)if(a[l]>d){g=l+h;break}return{xData:a.slice(f,g),yData:b.slice(f,g),start:f,end:g}},
generatePoints:function(){var a=this.options.data,b=this.data,c,d=this.processedXData,e=this.processedYData,f=this.pointClass,g=d.length,h=this.cropStart||0,l,m=this.hasGroupedData,q,p=[],k;b||m||(b=[],b.length=a.length,b=this.data=b);for(k=0;k<g;k++)l=h+k,m?p[k]=(new f).init(this,[d[k]].concat(ka(e[k]))):(b[l]?q=b[l]:a[l]!==A&&(b[l]=q=(new f).init(this,a[l],d[k])),p[k]=q);if(b&&(g!==(c=b.length)||m))for(k=0;k<c;k++)k!==h||m||(k+=g),b[k]&&(b[k].destroyElements(),b[k].plotX=A);this.data=b;this.points=
p},getExtremes:function(a){var b=this.yAxis,c=this.processedXData,d,e=[],f=0;d=this.xAxis.getExtremes();var g=d.min,h=d.max,l,m,q,p;a=a||this.stackedYData||this.processedYData;d=a.length;for(p=0;p<d;p++)if(m=c[p],q=a[p],l=null!==q&&q!==A&&(!b.isLog||q.length||0<q),m=this.getExtremesFromAll||this.cropped||(c[p+1]||m)>=g&&(c[p-1]||m)<=h,l&&m)if(l=q.length)for(;l--;)null!==q[l]&&(e[f++]=q[l]);else e[f++]=q;this.dataMin=k(void 0,w(e));this.dataMax=k(void 0,ua(e))},translate:function(){this.processedXData||
this.processData();this.generatePoints();for(var a=this.options,b=a.stacking,c=this.xAxis,d=c.categories,e=this.yAxis,f=this.points,g=f.length,h=!!this.modifyValue,l=a.pointPlacement,m="between"===l||U(l),q=a.threshold,a=0;a<g;a++){var p=f[a],x=p.x,n=p.y,r=p.low,t=b&&e.stacks[(this.negStacks&&n<q?"-":"")+this.stackKey];e.isLog&&0>=n&&(p.y=n=null);p.plotX=c.translate(x,0,0,0,1,l,"flags"===this.type);b&&this.visible&&t&&t[x]&&(t=t[x],n=t.points[this.index+","+a],r=n[0],n=n[1],0===r&&(r=k(q,e.min)),
e.isLog&&0>=r&&(r=null),p.total=p.stackTotal=t.total,p.percentage=t.total&&p.y/t.total*100,p.stackY=n,t.setOffset(this.pointXOffset||0,this.barW||0));p.yBottom=u(r)?e.translate(r,0,1,0,1):null;h&&(n=this.modifyValue(n,p));p.plotY="number"===typeof n&&Infinity!==n?e.translate(n,0,1,0,1):A;p.clientX=m?c.translate(x,0,0,0,1):p.plotX;p.negative=p.y<(q||0);p.category=d&&d[p.x]!==A?d[p.x]:p.x}this.getSegments()},animate:function(a){var b=this.chart,c=b.renderer,d;d=this.options.animation;var e=this.clipBox||
b.clipBox,f=b.inverted,g;d&&!J(d)&&(d=Na[this.type].animation);g=["_sharedClip",d.duration,d.easing,e.height].join();a?(a=b[g],d=b[g+"m"],a||(b[g]=a=c.clipRect(s(e,{width:0})),b[g+"m"]=d=c.clipRect(-99,f?-b.plotLeft:-b.plotTop,99,f?b.chartWidth:b.chartHeight)),this.group.clip(a),this.markerGroup.clip(d),this.sharedClipKey=g):((a=b[g])&&a.animate({width:b.plotSizeX},d),b[g+"m"]&&b[g+"m"].animate({width:b.plotSizeX+99},d),this.animate=null)},afterAnimate:function(){var a=this.chart,b=this.sharedClipKey,
c=this.group,d=this.clipBox;c&&!1!==this.options.clip&&(b&&d||c.clip(d?a.renderer.clipRect(d):a.clipRect),this.markerGroup.clip());W(this,"afterAnimate");setTimeout(function(){b&&a[b]&&(d||(a[b]=a[b].destroy()),a[b+"m"]&&(a[b+"m"]=a[b+"m"].destroy()))},100)},drawPoints:function(){var a,b=this.points,c=this.chart,d,e,f,g,h,l,m,q;d=this.options.marker;var p=this.pointAttr[""],x,n=this.markerGroup,r=k(d.enabled,this.activePointCount<0.5*this.xAxis.len/d.radius);if(!1!==d.enabled||this._hasPointMarkers)for(f=
b.length;f--;)g=b[f],d=ca(g.plotX),e=g.plotY,q=g.graphic,l=g.marker||{},a=r&&l.enabled===A||l.enabled,x=c.isInsidePlot(C(d),e,c.inverted),a&&e!==A&&!isNaN(e)&&null!==g.y?(a=g.pointAttr[g.selected?"select":""]||p,h=a.r,l=k(l.symbol,this.symbol),m=0===l.indexOf("url"),q?q[x?"show":"hide"](!0).animate(s({x:d-h,y:e-h},q.symbolName?{width:2*h,height:2*h}:{})):x&&(0<h||m)&&(g.graphic=c.renderer.symbol(l,d-h,e-h,2*h,2*h).attr(a).add(n))):q&&(g.graphic=q.destroy())},convertAttribs:function(a,b,c,d){var e=
this.pointAttrToOptions,f,g,h={};a=a||{};b=b||{};c=c||{};d=d||{};for(f in e)g=e[f],h[f]=k(a[g],b[f],c[f],d[f]);return h},getAttribs:function(){var a=this,b=a.options,c=Na[a.type].marker?b.marker:b,d=c.states,e=d.hover,f,g=a.color;f={stroke:g,fill:g};var h=a.points||[],l,m=[],k,p=a.pointAttrToOptions;k=a.hasPointSpecificOptions;var x=b.negativeColor,n=c.lineColor,r=c.fillColor;l=b.turboThreshold;var w;b.marker?(e.radius=e.radius||c.radius+2,e.lineWidth=e.lineWidth||c.lineWidth+1):e.color=e.color||
xa(e.color||g).brighten(e.brightness).get();m[""]=a.convertAttribs(c,f);t(["hover","select"],function(b){m[b]=a.convertAttribs(d[b],m[""])});a.pointAttr=m;g=h.length;if(!l||g<l||k)for(;g--;){l=h[g];(c=l.options&&l.options.marker||l.options)&&!1===c.enabled&&(c.radius=0);l.negative&&x&&(l.color=l.fillColor=x);k=b.colorByPoint||l.color;if(l.options)for(w in p)u(c[p[w]])&&(k=!0);k?(c=c||{},k=[],d=c.states||{},f=d.hover=d.hover||{},b.marker||(f.color=f.color||!l.options.color&&e.color||xa(l.color).brighten(f.brightness||
e.brightness).get()),f={color:l.color},r||(f.fillColor=l.color),n||(f.lineColor=l.color),k[""]=a.convertAttribs(s(f,c),m[""]),k.hover=a.convertAttribs(d.hover,m.hover,k[""]),k.select=a.convertAttribs(d.select,m.select,k[""])):k=m;l.pointAttr=k}},destroy:function(){var a=this,b=a.chart,c=/AppleWebKit\/533/.test(ra),d,e,f=a.data||[],g,h,l;W(a,"destroy");ea(a);t(a.axisTypes||[],function(b){if(l=a[b])T(l.series,a),l.isDirty=l.forceRedraw=!0});a.legendItem&&a.chart.legend.destroyItem(a);for(e=f.length;e--;)(g=
f[e])&&g.destroy&&g.destroy();a.points=null;clearTimeout(a.animationTimeout);t("area graph dataLabelsGroup group markerGroup tracker graphNeg areaNeg posClip negClip".split(" "),function(b){a[b]&&(d=c&&"group"===b?"hide":"destroy",a[b][d]())});b.hoverSeries===a&&(b.hoverSeries=null);T(b.series,a);for(h in a)delete a[h]},getSegmentPath:function(a){var b=this,c=[],d=b.options.step;t(a,function(e,f){var g=e.plotX,h=e.plotY,l;b.getPointSpline?c.push.apply(c,b.getPointSpline(a,e,f)):(c.push(f?"L":"M"),
d&&f&&(l=a[f-1],"right"===d?c.push(l.plotX,h):"center"===d?c.push((l.plotX+g)/2,l.plotY,(l.plotX+g)/2,h):c.push(g,l.plotY)),c.push(e.plotX,e.plotY))});return c},getGraphPath:function(){var a=this,b=[],c,d=[];t(a.segments,function(e){c=a.getSegmentPath(e);1<e.length?b=b.concat(c):d.push(e[0])});a.singlePoints=d;return a.graphPath=b},drawGraph:function(){var a=this,b=this.options,c=[["graph",b.lineColor||this.color]],d=b.lineWidth,e=b.dashStyle,f="square"!==b.linecap,g=this.getGraphPath(),h=b.negativeColor;
h&&c.push(["graphNeg",h]);t(c,function(c,h){var k=c[0],p=a[k];p?(La(p),p.animate({d:g})):d&&g.length&&(p={stroke:c[1],"stroke-width":d,fill:aa,zIndex:1},e?p.dashstyle=e:f&&(p["stroke-linecap"]=p["stroke-linejoin"]="round"),a[k]=a.chart.renderer.path(g).attr(p).add(a.group).shadow(!h&&b.shadow))})},clipNeg:function(){var a=this.options,b=this.chart,c=b.renderer,d=a.negativeColor||a.negativeFillColor,e,f=this.graph,g=this.area,h=this.posClip,l=this.negClip;e=b.chartWidth;var k=b.chartHeight,q=z(e,k),
p=this.yAxis;d&&(f||g)&&(d=C(p.toPixels(a.threshold||0,!0)),0>d&&(q-=d),a={x:0,y:0,width:q,height:d},q={x:0,y:d,width:q,height:q},b.inverted&&(a.height=q.y=b.plotWidth-d,c.isVML&&(a={x:b.plotWidth-d-b.plotLeft,y:0,width:e,height:k},q={x:d+b.plotLeft-e,y:0,width:b.plotLeft+d,height:e})),p.reversed?(b=q,e=a):(b=a,e=q),h?(h.animate(b),l.animate(e)):(this.posClip=h=c.clipRect(b),this.negClip=l=c.clipRect(e),f&&this.graphNeg&&(f.clip(h),this.graphNeg.clip(l)),g&&(g.clip(h),this.areaNeg.clip(l))))},invertGroups:function(){function a(){var a=
{width:b.yAxis.len,height:b.xAxis.len};t(["group","markerGroup"],function(c){b[c]&&b[c].attr(a).invert()})}var b=this,c=b.chart;b.xAxis&&(V(c,"resize",a),V(b,"destroy",function(){ea(c,"resize",a)}),a(),b.invertGroups=a)},plotGroup:function(a,b,c,d,e){var f=this[a],g=!f;g&&(this[a]=f=this.chart.renderer.g(b).attr({visibility:c,zIndex:d||0.1}).add(e));f[g?"attr":"animate"](this.getPlotBox());return f},getPlotBox:function(){var a=this.chart,b=this.xAxis,c=this.yAxis;a.inverted&&(b=c,c=this.xAxis);return{translateX:b?
b.left:a.plotLeft,translateY:c?c.top:a.plotTop,scaleX:1,scaleY:1}},render:function(){var a=this,b=a.chart,c,d=a.options,e=(c=d.animation)&&!!a.animate&&b.renderer.isSVG&&k(c.duration,500)||0,f=a.visible?"visible":"hidden",g=d.zIndex,h=a.hasRendered,l=b.seriesGroup;c=a.plotGroup("group","series",f,g,l);a.markerGroup=a.plotGroup("markerGroup","markers",f,g,l);e&&a.animate(!0);a.getAttribs();c.inverted=a.isCartesian?b.inverted:!1;a.drawGraph&&(a.drawGraph(),a.clipNeg());a.drawDataLabels&&a.drawDataLabels();
a.visible&&a.drawPoints();a.drawTracker&&!1!==a.options.enableMouseTracking&&a.drawTracker();b.inverted&&a.invertGroups();!1===d.clip||a.sharedClipKey||h||c.clip(b.clipRect);e&&a.animate();h||(e?a.animationTimeout=setTimeout(function(){a.afterAnimate()},e):a.afterAnimate());a.isDirty=a.isDirtyData=!1;a.hasRendered=!0},redraw:function(){var a=this.chart,b=this.isDirtyData,c=this.group,d=this.xAxis,e=this.yAxis;c&&(a.inverted&&c.attr({width:a.plotWidth,height:a.plotHeight}),c.animate({translateX:k(d&&
d.left,a.plotLeft),translateY:k(e&&e.top,a.plotTop)}));this.translate();this.setTooltipPoints&&this.setTooltipPoints(!0);this.render();b&&W(this,"updatedData")}};var rb=oa(Pa);wa.line=rb;s(sa,{Axis:Ca,Chart:Ia,Color:xa,Point:Ha,Tick:ba,Renderer:ya,Series:Pa,SVGElement:N,SVGRenderer:ya,arrayMin:w,arrayMax:ua,charts:ma,dateFormat:za,format:y,pathAnim:Ka,getOptions:function(){return Q},hasBidiBug:jb,isTouchDevice:ab,numberFormat:x,seriesTypes:wa,setOptions:function(a){Q=E(!0,Q,a);P();return Q},addEvent:V,
removeEvent:ea,createElement:ia,discardElement:qa,css:K,each:t,extend:s,map:eb,merge:E,pick:k,splat:ka,extendClass:oa,pInt:B,wrap:L,svg:$,canvas:ja,vml:!$&&!ja,product:"@product.name@",version:"@product.version@"})})();
(function(s){var E=s.Chart,B=s.addEvent,fa=s.removeEvent,J=s.createElement,Y=s.discardElement,U=s.css,R=s.merge,O=s.each,T=s.extend,u=Math.max,G=document,ka=window,k=s.isTouchDevice,K=s.Renderer.prototype.symbols,ia=s.getOptions(),oa;T(ia.lang,{printChart:"Print chart",downloadPNG:"Download PNG image",downloadJPEG:"Download JPEG image",downloadPDF:"Download PDF document",downloadSVG:"Download SVG vector image",contextButtonTitle:"Chart context menu"});ia.navigation={menuStyle:{border:"1px solid #A0A0A0",
background:"#FFFFFF",padding:"5px 0"},menuItemStyle:{padding:"0 10px",background:"none",color:"#303030",fontSize:k?"14px":"11px"},menuItemHoverStyle:{background:"#4572A5",color:"#FFFFFF"},buttonOptions:{symbolFill:"#E0E0E0",symbolSize:14,symbolStroke:"#666",symbolStrokeWidth:3,symbolX:12.5,symbolY:10.5,align:"right",buttonSpacing:3,height:22,theme:{fill:"white",stroke:"none"},verticalAlign:"top",width:24}};ia.exporting={type:"image/png",url:"http://export.highcharts.com/",buttons:{contextButton:{menuClassName:"highcharts-contextmenu",
symbol:"menu",_titleKey:"contextButtonTitle",menuItems:[{textKey:"printChart",onclick:function(){this.print()}},{separator:!0},{textKey:"downloadPNG",onclick:function(){this.exportChart()}},{textKey:"downloadJPEG",onclick:function(){this.exportChart({type:"image/jpeg"})}},{textKey:"downloadPDF",onclick:function(){this.exportChart({type:"application/pdf"})}},{textKey:"downloadSVG",onclick:function(){this.exportChart({type:"image/svg+xml"})}}]}}};s.post=function(k,r,s){var y;k=J("form",R({method:"post",
action:k,enctype:"multipart/form-data"},s),{display:"none"},G.body);for(y in r)J("input",{type:"hidden",name:y,value:r[y]},null,k);k.submit();Y(k)};T(E.prototype,{getSVG:function(k){var r=this,u,y,B,E,D=R(r.options,k);G.createElementNS||(G.createElementNS=function(k,r){return G.createElement(r)});k=J("div",null,{position:"absolute",top:"-9999em",width:r.chartWidth+"px",height:r.chartHeight+"px"},G.body);y=r.renderTo.style.width;E=r.renderTo.style.height;y=D.exporting.sourceWidth||D.chart.width||/px$/.test(y)&&
parseInt(y,10)||600;E=D.exporting.sourceHeight||D.chart.height||/px$/.test(E)&&parseInt(E,10)||400;T(D.chart,{animation:!1,renderTo:k,forExport:!0,width:y,height:E});D.exporting.enabled=!1;D.series=[];O(r.series,function(k){B=R(k.options,{animation:!1,showCheckbox:!1,visible:k.visible});B.isInternal||D.series.push(B)});u=new s.Chart(D,r.callback);O(["xAxis","yAxis"],function(k){O(r[k],function(r,x){var s=u[k][x],y=r.getExtremes(),D=y.userMin,y=y.userMax;!s||void 0===D&&void 0===y||s.setExtremes(D,
y,!0,!1)})});y=u.container.innerHTML;D=null;u.destroy();Y(k);y=y.replace(/zIndex="[^"]+"/g,"").replace(/isShadow="[^"]+"/g,"").replace(/symbolName="[^"]+"/g,"").replace(/jQuery[0-9]+="[^"]+"/g,"").replace(/url\([^#]+#/g,"url(#").replace(/<svg /,'<svg xmlns:xlink="http://www.w3.org/1999/xlink" ').replace(/ href=/g," xlink:href=").replace(/\n/," ").replace(/<\/svg>.*?$/,"</svg>").replace(/&nbsp;/g,"\u00a0").replace(/&shy;/g,"\u00ad").replace(/<IMG /g,"<image ").replace(/height=([^" ]+)/g,'height="$1"').replace(/width=([^" ]+)/g,
'width="$1"').replace(/hc-svg-href="([^"]+)">/g,'xlink:href="$1"/>').replace(/id=([^" >]+)/g,'id="$1"').replace(/class=([^" >]+)/g,'class="$1"').replace(/ transform /g," ").replace(/:(path|rect)/g,"$1").replace(/style="([^"]+)"/g,function(k){return k.toLowerCase()});return y=y.replace(/(url\(#highcharts-[0-9]+)&quot;/g,"$1").replace(/&quot;/g,"'")},exportChart:function(k,r){k=k||{};var u=this.options.exporting,u=this.getSVG(R({chart:{borderRadius:0}},u.chartOptions,r,{exporting:{sourceWidth:k.sourceWidth||
u.sourceWidth,sourceHeight:k.sourceHeight||u.sourceHeight}}));k=R(this.options.exporting,k);s.post(k.url,{filename:k.filename||"chart",type:k.type,width:k.width||0,scale:k.scale||2,svg:u},k.formAttributes)},print:function(){var k=this,r=k.container,s=[],u=r.parentNode,B=G.body,E=B.childNodes;k.isPrinting||(k.isPrinting=!0,O(E,function(k,r){1===k.nodeType&&(s[r]=k.style.display,k.style.display="none")}),B.appendChild(r),ka.focus(),ka.print(),setTimeout(function(){u.appendChild(r);O(E,function(k,r){1===
k.nodeType&&(k.style.display=s[r])});k.isPrinting=!1},1E3))},contextMenu:function(k,r,s,y,E,G,D){var w=this,K=w.options.navigation,pa=K.menuItemStyle,qa=w.chartWidth,I=w.chartHeight,Z="cache-"+k,P=w[Z],N=u(E,G),ba,R,Y,A=function(r){w.pointer.inClass(r.target,k)||R()};P||(w[Z]=P=J("div",{className:k},{position:"absolute",zIndex:1E3,padding:N+"px"},w.container),ba=J("div",null,T({MozBoxShadow:"3px 3px 10px #888",WebkitBoxShadow:"3px 3px 10px #888",boxShadow:"3px 3px 10px #888"},K.menuStyle),P),R=function(){U(P,
{display:"none"});D&&D.setState(0);w.openMenu=!1},B(P,"mouseleave",function(){Y=setTimeout(R,500)}),B(P,"mouseenter",function(){clearTimeout(Y)}),B(document,"mouseup",A),B(w,"destroy",function(){fa(document,"mouseup",A)}),O(r,function(k){if(k){var r=k.separator?J("hr",null,null,ba):J("div",{onmouseover:function(){U(this,K.menuItemHoverStyle)},onmouseout:function(){U(this,pa)},onclick:function(){R();k.onclick.apply(w,arguments)},innerHTML:k.text||w.options.lang[k.textKey]},T({cursor:"pointer"},pa),
ba);w.exportDivElements.push(r)}}),w.exportDivElements.push(ba,P),w.exportMenuWidth=P.offsetWidth,w.exportMenuHeight=P.offsetHeight);r={display:"block"};s+w.exportMenuWidth>qa?r.right=qa-s-E-N+"px":r.left=s-N+"px";y+G+w.exportMenuHeight>I&&"top"!==D.alignOptions.verticalAlign?r.bottom=I-y-N+"px":r.top=y+G-N+"px";U(P,r);w.openMenu=!0},addButton:function(k){var r=this,u=r.renderer,y=R(r.options.navigation.buttonOptions,k),B=y.onclick,E=y.menuItems,D,w,G={stroke:y.symbolStroke,fill:y.symbolFill},K=y.symbolSize||
12;r.btnCount||(r.btnCount=0);r.exportDivElements||(r.exportDivElements=[],r.exportSVGElements=[]);if(!1!==y.enabled){var J=y.theme,I=J.states,O=I&&I.hover,I=I&&I.select,P;delete J.states;B?P=function(){B.apply(r,arguments)}:E&&(P=function(){r.contextMenu(w.menuClassName,E,w.translateX,w.translateY,w.width,w.height,w);w.setState(2)});y.text&&y.symbol?J.paddingLeft=s.pick(J.paddingLeft,25):y.text||T(J,{width:y.width,height:y.height,padding:0});w=u.button(y.text,0,0,P,J,O,I).attr({title:r.options.lang[y._titleKey],
"stroke-linecap":"round"});w.menuClassName=k.menuClassName||"highcharts-menu-"+r.btnCount++;y.symbol&&(D=u.symbol(y.symbol,y.symbolX-K/2,y.symbolY-K/2,K,K).attr(T(G,{"stroke-width":y.symbolStrokeWidth||1,zIndex:1})).add(w));w.add().align(T(y,{width:w.width,x:s.pick(y.x,oa)}),!0,"spacingBox");oa+=(w.width+y.buttonSpacing)*("right"===y.align?-1:1);r.exportSVGElements.push(w,D)}},destroyExport:function(k){k=k.target;var r,s;for(r=0;r<k.exportSVGElements.length;r++)if(s=k.exportSVGElements[r])s.onclick=
s.ontouchstart=null,k.exportSVGElements[r]=s.destroy();for(r=0;r<k.exportDivElements.length;r++)s=k.exportDivElements[r],fa(s,"mouseleave"),k.exportDivElements[r]=s.onmouseout=s.onmouseover=s.ontouchstart=s.onclick=null,Y(s)}});K.menu=function(k,r,s,u){return["M",k,r+2.5,"L",k+s,r+2.5,"M",k,r+u/2+0.5,"L",k+s,r+u/2+0.5,"M",k,r+u-1.5,"L",k+s,r+u-1.5]};E.prototype.callbacks.push(function(k){var r,s=k.options.exporting,u=s.buttons;oa=0;if(!1!==s.enabled){for(r in u)k.addButton(u[r]);B(k,"destroy",k.destroyExport)}})})(Highcharts);
(function(s){})(Highcharts); 
